//! Rust port of `negfit/nikonlook_core.py`'s frozen bundle API
//! (`load_bundle` / `estimate_gains` / `apply`) — the "Nikon Scan look"
//! color pipeline: a shared 3x3 matrix + per-channel monotone curve model
//! (Layer B, unchanged between bundle versions — v1's and v2's model.json
//! are byte-identical, only Layer A was retrained) plus a per-frame
//! exposure gain estimator (Layer A) implemented in exactly the two
//! versions `nikonlook_core.py::_validate_layer_a` (lines 349-447)
//! recognizes: `percentile-stopgap-v1` (a blind percentile-span ratio
//! against one anchor frame) and `hybrid-exposure-ridge-v2`
//! (`nikonlook_core.py` lines 512-680: an optional hardware-exposure
//! inverse when the caller supplies exposure metadata, otherwise a scored
//! blind ridge regression over 48 raw distribution features). `load_bundle`
//! rejects any other Layer A method or Layer B model type instead of
//! silently applying wrong math.
//!
//! `load_bundle()` parses the **v2** bundle — the production default: v2's
//! blind path measures materially closer to the registered Nikon Scan
//! reference than v1 on live frames (see
//! `resources/nikonlook-v2/PROVENANCE.md` for the measured numbers).
//! `load_bundle_v1()` parses the v1 bundle, kept for the existing pinned v1
//! tests (Groups A-G below) and comparison tooling. Both share
//! `parse_bundle`.
//!
//! Both bundles' JSON matrices/curves are vendored as compiled-in engine
//! resources under `engine/resources/nikonlook-v1/` and
//! `engine/resources/nikonlook-v2/`, embedded via `include_str!` — no
//! runtime file path, no network access. The numeric model targets Adobe
//! RGB-family encoded values, but ScanStudio does not redistribute or embed
//! a Nikon ICC profile. See each bundle directory's `PROVENANCE.md` for the
//! vendoring record and the owner's licensing grant citation.
//!
//! Every numeric literal in this module's v1 test suite (Groups A-G) was
//! generated by directly invoking the real `nikonlook_core.py` against the
//! real `nikonlook-v1` bundle (see plan 14-01's `<behavior>` block); the v2
//! test suite (Groups H-O) was generated the same way against the real
//! `nikonlook-v2` bundle. This is a faithful numeric port of a verified
//! reference implementation, not a reimplementation from first principles.

use serde::Deserialize;

// ---------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------

/// Mirrors `app/ScanStudio/engine/src/parity/types.rs`'s `ParityError`
/// shape. No `Io` variant — this module never touches the filesystem at
/// runtime (bundle data is compiled in via `include_str!`).
#[derive(Debug)]
pub enum NikonlookError {
    Json(serde_json::Error),
    Invalid(String),
}

impl std::fmt::Display for NikonlookError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            NikonlookError::Json(err) => write!(f, "json error: {err}"),
            NikonlookError::Invalid(message) => write!(f, "invalid nikonlook bundle: {message}"),
        }
    }
}

impl std::error::Error for NikonlookError {}

impl From<serde_json::Error> for NikonlookError {
    fn from(err: serde_json::Error) -> Self {
        NikonlookError::Json(err)
    }
}

// ---------------------------------------------------------------------
// MonotoneCurve
// ---------------------------------------------------------------------

/// One Layer-B monotone curve (R, G, or B). `.apply(x)` must match NumPy's
/// `np.interp(x, grid_x, grid_y)` exactly: grid_x is sorted ascending
/// (verified: 257 points in the nikonlook-v1 bundle, strictly increasing).
/// If x <= grid_x[0], return grid_y[0]. If x >= grid_x[last], return
/// grid_y[last]. Otherwise linearly interpolate between the two bracketing
/// grid points. (`decreasing` from the Python source is provenance-only and
/// is never read by `.apply()` — confirmed by reading nikonlook_core.py's
/// `MonotoneCurveLite.apply`, which always does `np.interp(x, grid_x,
/// grid_y)` regardless of the `decreasing` flag — so this port omits the
/// field from this struct entirely.)
pub struct MonotoneCurve {
    pub grid_x: Vec<f64>,
    pub grid_y: Vec<f64>,
}

impl MonotoneCurve {
    pub fn apply(&self, x: f64) -> f64 {
        let n = self.grid_x.len();
        debug_assert!(n > 0, "MonotoneCurve grid must be non-empty");
        if n == 1 {
            return self.grid_y[0];
        }
        if x <= self.grid_x[0] {
            return self.grid_y[0];
        }
        if x >= self.grid_x[n - 1] {
            return self.grid_y[n - 1];
        }
        // First index where grid_x[i] > x. Since grid_x is strictly
        // ascending and grid_x[0] < x < grid_x[n-1] here, `hi` is in
        // 1..=(n-1) — matches NumPy's np.interp bracketing for a strictly
        // increasing grid, including the exact-grid-point case (frac = 0).
        let hi = self.grid_x.partition_point(|&gx| gx <= x);
        let lo = hi - 1;
        let x0 = self.grid_x[lo];
        let x1 = self.grid_x[hi];
        let y0 = self.grid_y[lo];
        let y1 = self.grid_y[hi];
        let span = x1 - x0;
        if span <= 0.0 {
            // Degenerate/duplicate grid_x — not expected in the real
            // bundle (verified strictly increasing), but np.interp
            // returns the right-hand sample in this case.
            return y1;
        }
        let frac = (x - x0) / span;
        y0 + (y1 - y0) * frac
    }
}

// ---------------------------------------------------------------------
// Layer-A method/schema tags — mirrors nikonlook_core.py's own frozen
// literals (lines 98-107) so a malformed or future bundle fails loudly
// instead of being interpreted as the wrong method.
// ---------------------------------------------------------------------

const LAYER_A_V1_METHOD: &str = "percentile-stopgap-v1";
const LAYER_A_V2_METHOD: &str = "hybrid-exposure-ridge-v2";
const LAYER_A_V2_METADATA_METHOD: &str = "inverse-hardware-exposure-v1";
const LAYER_A_V2_BLIND_METHOD: &str = "log-ridge-raw-features-v1";
const LAYER_A_V2_FEATURE_SCHEMA: &str = "raw-rail-quantiles-log-v1";
const LAYER_A_V2_FEATURE_COUNT: usize = 48;

/// `np.percentile` targets for v2's blind raw-feature schema — mirrors
/// `nikonlook_core.py`'s `LAYER_A_V2_QUANTILES` (lines 103-106) exactly,
/// including order.
const LAYER_A_V2_QUANTILES: [f64; 13] =
    [1.0, 2.0, 5.0, 10.0, 20.0, 35.0, 50.0, 65.0, 80.0, 90.0, 95.0, 98.0, 99.0];

/// Index pairs into the 13 quantiles above for the 3 span features (widest
/// to narrowest) — mirrors `LAYER_A_V2_SPAN_INDEX_PAIRS` (line 107) exactly.
const LAYER_A_V2_SPAN_INDEX_PAIRS: [(usize, usize); 3] = [(0, 12), (1, 11), (2, 10)];

// ---------------------------------------------------------------------
// Bundle
// ---------------------------------------------------------------------

/// A loaded nikonlook bundle. Fields are private — only load_bundle /
/// estimate_gains / apply (this module's frozen API surface) touch them.
/// quality_tier/bundle_version are exposed for future provenance/debug/UI
/// use even though nothing calls them yet in this phase.
pub struct Bundle {
    matrix: [[f64; 3]; 3], // "M" from model.json, applied as-is (not transposed) — see algorithm note below
    curves: [MonotoneCurve; 3], // R, G, B order, from model.json's "curves"
    layer_a: LayerA,
    pub quality_tier: String,   // manifest.json "quality_tier"
    pub bundle_version: String, // manifest.json "bundle_version"
}

/// Layer A, dispatched by `layer_a.json`'s own `method` field (see this
/// module's doc comment). `estimate_gains` matches on this enum rather than
/// a stringly-typed method field, so an unsupported method can never reach
/// gain estimation — `parse_bundle` already rejects it before a `Bundle`
/// exists.
enum LayerA {
    V1(LayerAV1),
    V2(LayerAV2),
}

struct LayerAV1 {
    lo_pct: f64,
    hi_pct: f64,
    rail_lo_fraction: f64,
    rail_hi_fraction: f64,
    reference_lo: [f64; 3],
    reference_hi: [f64; 3],
    reference_k: [f64; 3],
    gain_bounds: (f64, f64),
}

/// v2's optional hardware-exposure inverse — mirrors `layer_a.json`'s
/// `metadata_estimator` object (`inverse-hardware-exposure-v1`).
struct MetadataEstimatorV1 {
    reference_exposure_10ns: [f64; 3],
    reference_gain: [f64; 3],
    gain_bounds: (f64, f64),
}

/// v2's scored blind fallback — mirrors `layer_a.json`'s `blind_fallback`
/// object (`log-ridge-raw-features-v1`): a standardized 48-feature
/// log-ridge regression to a per-channel log-gain.
struct BlindFallbackV1 {
    sample_stride: usize,
    rail_lo_fraction: f64,
    rail_hi_fraction: f64,
    feature_mean: Vec<f64>,
    feature_scale: Vec<f64>,
    log_gain_intercept: [f64; 3],
    coefficients: Vec<[f64; 3]>,
    gain_bounds: (f64, f64),
}

struct LayerAV2 {
    metadata: MetadataEstimatorV1,
    blind: BlindFallbackV1,
}

// ---------------------------------------------------------------------
// Deserialization DTOs — only the fields this module actually reads.
// serde ignores the many other fields present in the real JSON
// automatically since none of these DTOs sets `deny_unknown_fields`.
// ---------------------------------------------------------------------

#[derive(Deserialize)]
struct ModelDto {
    model: String,
    #[serde(rename = "M")]
    m: Vec<Vec<f64>>,
    curves: Vec<CurveDto>,
}

#[derive(Deserialize)]
struct CurveDto {
    grid_x: Vec<f64>,
    grid_y: Vec<f64>,
    // Provenance-only in the Python source (see MonotoneCurve's doc
    // comment above) — deserialized to mirror the on-disk shape 1:1 but
    // deliberately never read past that.
    #[allow(dead_code)]
    decreasing: bool,
}

#[derive(Deserialize)]
struct LayerADto {
    // No `method` field — dispatch already happened via
    // `LayerAMethodProbeDto` before this DTO is parsed; serde ignores the
    // JSON's "method" key here same as every other field this DTO omits.
    lo_pct: f64,
    hi_pct: f64,
    rail_lo_fraction: f64,
    rail_hi_fraction: f64,
    gain_bounds: Vec<f64>,
    reference_lo: Vec<f64>,
    reference_hi: Vec<f64>,
    reference_k: Vec<f64>,
}

/// Reads only `layer_a.json`'s top-level `method` field, before deciding
/// which of `LayerADto` (v1) / `LayerAV2Dto` (v2) to parse the same string
/// into. Both real shapes (and every hand-built malformed fixture in this
/// module's Group G/O tests) carry this field, and serde ignores the many
/// fields this probe doesn't declare.
#[derive(Deserialize)]
struct LayerAMethodProbeDto {
    method: String,
}

#[derive(Deserialize)]
struct LayerAV2Dto {
    metadata_estimator: MetadataEstimatorDto,
    blind_fallback: BlindFallbackDto,
}

#[derive(Deserialize)]
struct MetadataEstimatorDto {
    method: String,
    reference_exposure_10ns: Vec<f64>,
    reference_gain: Vec<f64>,
    gain_bounds: Vec<f64>,
}

#[derive(Deserialize)]
struct BlindFallbackDto {
    method: String,
    feature_schema: String,
    sample_stride: usize,
    rail_lo_fraction: f64,
    rail_hi_fraction: f64,
    gain_bounds: Vec<f64>,
    feature_mean: Vec<f64>,
    feature_scale: Vec<f64>,
    log_gain_intercept: Vec<f64>,
    coefficients: Vec<Vec<f64>>,
}

#[derive(Deserialize)]
struct ManifestDto {
    bundle_version: String,
    quality_tier: String,
    layer_a_method: Option<String>,
}

// ---------------------------------------------------------------------
// Embedded bundle data — hermetic, no runtime file path, no network.
// ---------------------------------------------------------------------

const MODEL_JSON_V1: &str = include_str!("../../resources/nikonlook-v1/model.json");
const LAYER_A_JSON_V1: &str = include_str!("../../resources/nikonlook-v1/layer_a.json");
const MANIFEST_JSON_V1: &str = include_str!("../../resources/nikonlook-v1/manifest.json");

const MODEL_JSON_V2: &str = include_str!("../../resources/nikonlook-v2/model.json");
const LAYER_A_JSON_V2: &str = include_str!("../../resources/nikonlook-v2/layer_a.json");
const MANIFEST_JSON_V2: &str = include_str!("../../resources/nikonlook-v2/manifest.json");

/// Parses the three embedded v2 JSON strings (model.json, layer_a.json,
/// manifest.json) via include_str! — this is the production default: v2's
/// blind path measures materially closer to the registered Nikon Scan
/// reference than v1 on live frames (see
/// `resources/nikonlook-v2/PROVENANCE.md` for the measured numbers).
/// Returns `NikonlookError::Invalid` (not a panic) on a malformed bundle —
/// see `parse_bundle`.
pub fn load_bundle() -> Result<Bundle, NikonlookError> {
    parse_bundle(MODEL_JSON_V2, LAYER_A_JSON_V2, MANIFEST_JSON_V2)
}

/// Parses the three embedded v1 JSON strings. Kept for the existing pinned
/// v1 tests (Groups A-G below) and any comparison tooling that still wants
/// the original `percentile-stopgap-v1` estimator; not the production
/// default — see `load_bundle`.
pub fn load_bundle_v1() -> Result<Bundle, NikonlookError> {
    parse_bundle(MODEL_JSON_V1, LAYER_A_JSON_V1, MANIFEST_JSON_V1)
}

/// Internal parse/validate helper shared by `load_bundle` / `load_bundle_v1`
/// (real embedded data) and this module's own tests (hand-built malformed
/// JSON strings) — see the Group G/O tests below. Dispatches on
/// `layer_a.json`'s own `method` field: returns `NikonlookError::Invalid`
/// (not a panic) if model.json's "model" field != "DirectPF", if the method
/// names neither supported Layer-A version, or if the manifest's
/// `layer_a_method` (when present) disagrees with layer_a.json's own method
/// — mirroring `nikonlook_core.py::_validate_layer_a`'s guard behavior for
/// unsupported or inconsistent bundles, never silently applying wrong math.
fn parse_bundle(
    model_json: &str,
    layer_a_json: &str,
    manifest_json: &str,
) -> Result<Bundle, NikonlookError> {
    let model: ModelDto = serde_json::from_str(model_json)?;
    let method_probe: LayerAMethodProbeDto = serde_json::from_str(layer_a_json)?;
    let manifest: ManifestDto = serde_json::from_str(manifest_json)?;
    let method = method_probe.method;

    if model.model != "DirectPF" {
        return Err(NikonlookError::Invalid(format!(
            "model.json: unrecognized Layer B model type {:?} — this port only applies \
             DirectPF-format models (fit37/model_directpf.py's serialization)",
            model.model
        )));
    }
    if method != LAYER_A_V1_METHOD && method != LAYER_A_V2_METHOD {
        return Err(NikonlookError::Invalid(format!(
            "layer_a.json: unsupported Layer-A method {method:?} — supported methods are \
             {LAYER_A_V1_METHOD:?} and {LAYER_A_V2_METHOD:?}"
        )));
    }
    if let Some(manifest_method) = &manifest.layer_a_method {
        if manifest_method != &method {
            return Err(NikonlookError::Invalid(format!(
                "manifest layer_a_method {manifest_method:?} does not match layer_a.json \
                 method {method:?}"
            )));
        }
    }

    if model.m.len() != 3 || !model.m.iter().all(|row| row.len() == 3) {
        return Err(NikonlookError::Invalid(format!(
            "model.json: expected a 3x3 'M' matrix, got {} row(s)",
            model.m.len()
        )));
    }
    let mut matrix = [[0.0f64; 3]; 3];
    for (i, row) in model.m.iter().enumerate() {
        matrix[i] = [row[0], row[1], row[2]];
    }

    if model.curves.len() != 3 {
        return Err(NikonlookError::Invalid(format!(
            "model.json: expected exactly 3 curves (R,G,B), got {}",
            model.curves.len()
        )));
    }
    let curves_vec: Vec<MonotoneCurve> = model
        .curves
        .into_iter()
        .map(|curve| MonotoneCurve {
            grid_x: curve.grid_x,
            grid_y: curve.grid_y,
        })
        .collect();
    let curves: [MonotoneCurve; 3] = curves_vec
        .try_into()
        .map_err(|_| NikonlookError::Invalid("model.json: expected exactly 3 curves (R,G,B)".to_string()))?;

    let layer_a = if method == LAYER_A_V1_METHOD {
        let layer_a_dto: LayerADto = serde_json::from_str(layer_a_json)?;

        let reference_lo = fixed3(&layer_a_dto.reference_lo, "layer_a.json:reference_lo")?;
        let reference_hi = fixed3(&layer_a_dto.reference_hi, "layer_a.json:reference_hi")?;
        let reference_k = fixed3(&layer_a_dto.reference_k, "layer_a.json:reference_k")?;
        let gain_bounds = fixed2(&layer_a_dto.gain_bounds, "layer_a.json:gain_bounds")?;

        LayerA::V1(LayerAV1 {
            lo_pct: layer_a_dto.lo_pct,
            hi_pct: layer_a_dto.hi_pct,
            rail_lo_fraction: layer_a_dto.rail_lo_fraction,
            rail_hi_fraction: layer_a_dto.rail_hi_fraction,
            reference_lo,
            reference_hi,
            reference_k,
            gain_bounds: (gain_bounds[0], gain_bounds[1]),
        })
    } else {
        let layer_a_dto: LayerAV2Dto = serde_json::from_str(layer_a_json)?;
        LayerA::V2(build_layer_a_v2(layer_a_dto)?)
    };

    Ok(Bundle {
        matrix,
        curves,
        layer_a,
        quality_tier: manifest.quality_tier,
        bundle_version: manifest.bundle_version,
    })
}

/// Validates a field's value slice has exactly 3 elements, converting into
/// a fixed-size array — `NikonlookError::Invalid` with a clear message
/// (naming the field) on any shape mismatch.
fn fixed3(values: &[f64], field: &str) -> Result<[f64; 3], NikonlookError> {
    if values.len() != 3 {
        return Err(NikonlookError::Invalid(format!(
            "{field}: expected 3 values, got {}",
            values.len()
        )));
    }
    Ok([values[0], values[1], values[2]])
}

/// Same as `fixed3` but for 2-element fields (e.g. `gain_bounds`).
fn fixed2(values: &[f64], field: &str) -> Result<[f64; 2], NikonlookError> {
    if values.len() != 2 {
        return Err(NikonlookError::Invalid(format!(
            "{field}: expected 2 values, got {}",
            values.len()
        )));
    }
    Ok([values[0], values[1]])
}

// ---------------------------------------------------------------------
// v2 field validation — mirrors nikonlook_core.py's `_finite_array` /
// `_finite_scalar` / `_validated_gain_bounds` (lines 308-328), used only by
// the v2 branch. v1's `fixed3`/`fixed2` above predate this and are left as
// they are — the existing v1 tests must keep passing unchanged.
// ---------------------------------------------------------------------

/// Validates a v2 field's value slice has exactly `len` finite values (and,
/// if `positive`, all > 0) — mirrors `_finite_array`.
fn finite_slice(values: &[f64], len: usize, field: &str, positive: bool) -> Result<(), NikonlookError> {
    if values.len() != len {
        return Err(NikonlookError::Invalid(format!(
            "{field}: expected {len} value(s), got {}",
            values.len()
        )));
    }
    if !values.iter().all(|v| v.is_finite()) {
        return Err(NikonlookError::Invalid(format!("{field}: values must be finite")));
    }
    if positive && values.iter().any(|&v| v <= 0.0) {
        return Err(NikonlookError::Invalid(format!("{field}: values must be positive")));
    }
    Ok(())
}

/// `finite_slice` plus a 3-element array conversion, for v2's 3-wide
/// per-channel fields (`reference_exposure_10ns`, `reference_gain`,
/// `log_gain_intercept`).
fn finite_array3(values: &[f64], field: &str, positive: bool) -> Result<[f64; 3], NikonlookError> {
    finite_slice(values, 3, field, positive)?;
    Ok([values[0], values[1], values[2]])
}

/// Mirrors `_validated_gain_bounds`: 2 finite positive values, lower
/// strictly less than upper.
fn validated_gain_bounds(values: &[f64], field: &str) -> Result<(f64, f64), NikonlookError> {
    finite_slice(values, 2, field, true)?;
    let (lo, hi) = (values[0], values[1]);
    if lo >= hi {
        return Err(NikonlookError::Invalid(format!(
            "{field}: expected lower bound < upper bound, got {lo} >= {hi}"
        )));
    }
    Ok((lo, hi))
}

/// Validates v2's `coefficients` field: exactly `rows` rows, each exactly 3
/// finite values — mirrors `_finite_array`'s `(LAYER_A_V2_FEATURE_COUNT, 3)`
/// shape check.
fn finite_matrix_rows3(values: &[Vec<f64>], rows: usize, field: &str) -> Result<Vec<[f64; 3]>, NikonlookError> {
    if values.len() != rows {
        return Err(NikonlookError::Invalid(format!(
            "{field}: expected {rows} rows, got {}",
            values.len()
        )));
    }
    let mut out = Vec::with_capacity(rows);
    for (i, row) in values.iter().enumerate() {
        if row.len() != 3 || !row.iter().all(|v| v.is_finite()) {
            return Err(NikonlookError::Invalid(format!(
                "{field}: row {i} must have exactly 3 finite values, got {row:?}"
            )));
        }
        out.push([row[0], row[1], row[2]]);
    }
    Ok(out)
}

/// Validates and constructs v2's Layer A from its parsed DTO — mirrors
/// `nikonlook_core.py::_validate_layer_a`'s v2 branch (lines 376-447).
fn build_layer_a_v2(dto: LayerAV2Dto) -> Result<LayerAV2, NikonlookError> {
    const PREFIX: &str = "layer_a.json";

    if dto.metadata_estimator.method != LAYER_A_V2_METADATA_METHOD {
        return Err(NikonlookError::Invalid(format!(
            "{PREFIX}: unsupported metadata estimator {:?}",
            dto.metadata_estimator.method
        )));
    }
    let reference_exposure_10ns = finite_array3(
        &dto.metadata_estimator.reference_exposure_10ns,
        &format!("{PREFIX}:metadata_estimator.reference_exposure_10ns"),
        true,
    )?;
    let reference_gain = finite_array3(
        &dto.metadata_estimator.reference_gain,
        &format!("{PREFIX}:metadata_estimator.reference_gain"),
        true,
    )?;
    let metadata_gain_bounds = validated_gain_bounds(
        &dto.metadata_estimator.gain_bounds,
        &format!("{PREFIX}:metadata_estimator.gain_bounds"),
    )?;

    if dto.blind_fallback.method != LAYER_A_V2_BLIND_METHOD {
        return Err(NikonlookError::Invalid(format!(
            "{PREFIX}: unsupported blind estimator {:?}",
            dto.blind_fallback.method
        )));
    }
    if dto.blind_fallback.feature_schema != LAYER_A_V2_FEATURE_SCHEMA {
        return Err(NikonlookError::Invalid(format!(
            "{PREFIX}: unsupported blind feature schema {:?}",
            dto.blind_fallback.feature_schema
        )));
    }
    if dto.blind_fallback.sample_stride < 1 {
        return Err(NikonlookError::Invalid(format!(
            "{PREFIX}: blind sample_stride must be a positive integer"
        )));
    }
    let rail_lo = dto.blind_fallback.rail_lo_fraction;
    let rail_hi = dto.blind_fallback.rail_hi_fraction;
    if !(0.0 <= rail_lo && rail_lo < rail_hi && rail_hi <= 1.0) {
        return Err(NikonlookError::Invalid(format!(
            "{PREFIX}: expected blind rail fractions to satisfy 0 <= lo < hi <= 1"
        )));
    }
    let blind_gain_bounds = validated_gain_bounds(
        &dto.blind_fallback.gain_bounds,
        &format!("{PREFIX}:blind_fallback.gain_bounds"),
    )?;
    finite_slice(
        &dto.blind_fallback.feature_mean,
        LAYER_A_V2_FEATURE_COUNT,
        &format!("{PREFIX}:blind_fallback.feature_mean"),
        false,
    )?;
    finite_slice(
        &dto.blind_fallback.feature_scale,
        LAYER_A_V2_FEATURE_COUNT,
        &format!("{PREFIX}:blind_fallback.feature_scale"),
        true,
    )?;
    let log_gain_intercept = finite_array3(
        &dto.blind_fallback.log_gain_intercept,
        &format!("{PREFIX}:blind_fallback.log_gain_intercept"),
        false,
    )?;
    let coefficients = finite_matrix_rows3(
        &dto.blind_fallback.coefficients,
        LAYER_A_V2_FEATURE_COUNT,
        &format!("{PREFIX}:blind_fallback.coefficients"),
    )?;

    Ok(LayerAV2 {
        metadata: MetadataEstimatorV1 {
            reference_exposure_10ns,
            reference_gain,
            gain_bounds: metadata_gain_bounds,
        },
        blind: BlindFallbackV1 {
            sample_stride: dto.blind_fallback.sample_stride,
            rail_lo_fraction: rail_lo,
            rail_hi_fraction: rail_hi,
            feature_mean: dto.blind_fallback.feature_mean,
            feature_scale: dto.blind_fallback.feature_scale,
            log_gain_intercept,
            coefficients,
            gain_bounds: blind_gain_bounds,
        },
    })
}

// ---------------------------------------------------------------------
// Percentile primitive (mirrors nikonlook_core.py's unclipped_percentiles)
// ---------------------------------------------------------------------

/// NumPy's default "linear" percentile interpolation on an ALREADY SORTED
/// ascending slice. `p` is in [0, 100].
fn percentile_linear(sorted: &[f64], p: f64) -> f64 {
    let n = sorted.len();
    debug_assert!(n > 0, "percentile_linear requires a non-empty slice");
    if n == 1 {
        return sorted[0];
    }
    let idx = (p / 100.0) * (n - 1) as f64;
    let lo_idx = idx.floor() as usize;
    let hi_idx = idx.ceil() as usize;
    if lo_idx == hi_idx {
        return sorted[lo_idx];
    }
    let frac = idx - lo_idx as f64;
    sorted[lo_idx] * (1.0 - frac) + sorted[hi_idx] * frac
}

/// Per-channel [lo_pct, hi_pct] percentile of a single-channel raw-linear
/// slice, excluding samples at/near the sensor rails (<= rail_lo_fraction
/// or >= rail_hi_fraction), so a handful of blown highlights or a
/// near-black border don't skew the anchor points. Falls back to the
/// unmasked population if fewer than 1000 unclipped samples remain (uses
/// the ENTIRE original slice in that case, not the small filtered subset).
fn unclipped_percentiles(
    channel: &[f64],
    lo_pct: f64,
    hi_pct: f64,
    rail_lo_fraction: f64,
    rail_hi_fraction: f64,
) -> (f64, f64) {
    let masked: Vec<f64> = channel
        .iter()
        .copied()
        .filter(|&v| v > rail_lo_fraction && v < rail_hi_fraction)
        .collect();
    let mut vals = if masked.len() >= 1000 { masked } else { channel.to_vec() };
    // f64::total_cmp, not partial_cmp().unwrap(), so a stray NaN cannot
    // panic the sort.
    vals.sort_by(f64::total_cmp);
    let lo = percentile_linear(&vals, lo_pct);
    let hi = percentile_linear(&vals, hi_pct);
    (lo, hi)
}

// ---------------------------------------------------------------------
// v2 blind feature extraction (mirrors nikonlook_core.py's
// `_layer_a_v2_features`, lines 512-559)
// ---------------------------------------------------------------------

/// Runtime feature extraction for v2's blind fallback — mirrors
/// `nikonlook_core.py::_layer_a_v2_features` for the (H,W,3) input case
/// only (the engine never calls this with a flat (N,3) list; Python's
/// `_as_rows`-style (N,3) branch has no equivalent here).
///
/// `raw.len()` must be an exact multiple of `width` — engine data always is
/// (every raw buffer this module receives is a decoded (H,W,3) raster
/// flattened row-major); failing loudly on a mismatch matches the Python
/// reshape contract (`raw.reshape(-1, 3)` on a non-rectangular array raises
/// too) rather than silently misinterpreting the buffer.
fn layer_a_v2_features(raw: &[[f64; 3]], width: usize, blind: &BlindFallbackV1) -> Result<[f64; 48], NikonlookError> {
    if width == 0 || raw.len() % width != 0 {
        return Err(NikonlookError::Invalid(format!(
            "layer_a_v2_features: raw length {} is not an exact multiple of width {width}",
            raw.len()
        )));
    }
    let height = raw.len() / width;
    let stride = blind.sample_stride;

    let mut values: Vec<f64> = Vec::with_capacity(LAYER_A_V2_FEATURE_COUNT);
    for c in 0..3 {
        // Row-major sampled order, identical to NumPy's `raw[::s, ::s, :]`
        // (y outer, x inner, both ascending).
        let mut channel: Vec<f64> = Vec::new();
        for y in (0..height).step_by(stride) {
            for x in (0..width).step_by(stride) {
                let value = raw[y * width + x][c];
                if value.is_finite() {
                    channel.push(value);
                }
            }
        }
        if channel.is_empty() {
            return Err(NikonlookError::Invalid(format!(
                "layer_a_v2_features: raw channel {} has no finite samples",
                ['R', 'G', 'B'][c]
            )));
        }

        let masked: Vec<f64> = channel
            .iter()
            .copied()
            .filter(|&v| v > blind.rail_lo_fraction && v < blind.rail_hi_fraction)
            .collect();
        let mut population = if masked.len() >= 1000 { masked } else { channel };
        // f64::total_cmp, not partial_cmp().unwrap(), so a stray NaN cannot
        // panic the sort.
        population.sort_by(f64::total_cmp);

        // One sort, 13 percentile_linear lookups on the same sorted slice.
        let quantiles: Vec<f64> = LAYER_A_V2_QUANTILES
            .iter()
            .map(|&p| percentile_linear(&population, p))
            .collect();
        values.extend_from_slice(&quantiles);
        // Spans BEFORE log: q[12]-q[0], q[11]-q[1], q[10]-q[2].
        for &(lo, hi) in LAYER_A_V2_SPAN_INDEX_PAIRS.iter() {
            values.push(quantiles[hi] - quantiles[lo]);
        }
    }
    debug_assert_eq!(values.len(), LAYER_A_V2_FEATURE_COUNT);

    let mut features = [0.0f64; 48];
    for (i, &v) in values.iter().enumerate() {
        features[i] = v.max(1e-9).ln();
    }
    Ok(features)
}

// ---------------------------------------------------------------------
// Layer A -- estimate_gains (dispatches percentile-stopgap-v1 /
// hybrid-exposure-ridge-v2)
// ---------------------------------------------------------------------

/// Per-frame exposure gain estimate ("Layer A"), dispatched by the loaded
/// bundle's method (see this module's doc comment). `raw` is scanner-linear
/// RGB in [0,1] (16-bit raw counts / 65535), one [R,G,B] triple per pixel,
/// row-major, `width` wide (height is inferred as `raw.len() / width`).
/// `LayerA::V1` ignores both `width` and `exposure_10ns`.
///
/// `exposure_10ns` is the caller's per-channel hardware exposure duration
/// in 10ns ticks (mirrors nikonlook_core.py's `meta["exposure_10ns"]`),
/// `None` when unavailable. `LayerA::V2` uses it when present (the
/// `inverse-hardware-exposure-v1` path — the caller must guarantee each
/// component is finite and > 0; only `debug_assert!`-checked, since this is
/// a hot per-frame call and the bundle's own gain_bounds clamp already
/// contains a bad ratio's blast radius); otherwise v2 falls back to
/// `log-ridge-raw-features-v1`, its scored blind estimator, which is the
/// only path that can return `Err` (a degenerate `raw`/`width` pairing —
/// see `layer_a_v2_features` — unreachable for real engine data, which is
/// always an exact (H,W,3) raster).
///
/// Returns (3,) gain, clamped to the active method's own gain_bounds.
pub fn estimate_gains(
    raw: &[[f64; 3]],
    width: usize,
    exposure_10ns: Option<[f64; 3]>,
    bundle: &Bundle,
) -> Result<[f64; 3], NikonlookError> {
    match &bundle.layer_a {
        LayerA::V1(la) => {
            let mut k = [0.0f64; 3];
            for c in 0..3 {
                let channel: Vec<f64> = raw.iter().map(|px| px[c]).collect();
                let (in_lo, in_hi) = unclipped_percentiles(
                    &channel,
                    la.lo_pct,
                    la.hi_pct,
                    la.rail_lo_fraction,
                    la.rail_hi_fraction,
                );
                let in_span = (in_hi - in_lo).max(1e-9);
                let ref_span = (la.reference_hi[c] - la.reference_lo[c]).max(1e-9);
                k[c] = la.reference_k[c] * (ref_span / in_span);
            }
            let (lo_bound, hi_bound) = la.gain_bounds;
            for value in k.iter_mut() {
                *value = value.clamp(lo_bound, hi_bound);
            }
            Ok(k)
        }
        LayerA::V2(la) => {
            if let Some(exposure) = exposure_10ns {
                debug_assert!(
                    exposure.iter().all(|&value| value.is_finite() && value > 0.0),
                    "exposure_10ns components must be finite and positive"
                );
                let mut gain = [0.0f64; 3];
                for c in 0..3 {
                    gain[c] =
                        la.metadata.reference_gain[c] * la.metadata.reference_exposure_10ns[c] / exposure[c];
                }
                let (lo_bound, hi_bound) = la.metadata.gain_bounds;
                for value in gain.iter_mut() {
                    *value = value.clamp(lo_bound, hi_bound);
                }
                Ok(gain)
            } else {
                let features = layer_a_v2_features(raw, width, &la.blind)?;
                let mut standardized = [0.0f64; 48];
                for i in 0..48 {
                    standardized[i] = (features[i] - la.blind.feature_mean[i]) / la.blind.feature_scale[i];
                }
                let mut gain = [0.0f64; 3];
                for c in 0..3 {
                    let mut sum = la.blind.log_gain_intercept[c];
                    for (i, value) in standardized.iter().enumerate() {
                        sum += value * la.blind.coefficients[i][c];
                    }
                    gain[c] = sum.exp();
                }
                let (lo_bound, hi_bound) = la.blind.gain_bounds;
                for value in gain.iter_mut() {
                    *value = value.clamp(lo_bound, hi_bound);
                }
                Ok(gain)
            }
        }
    }
}

// ---------------------------------------------------------------------
// Layer B -- apply
// ---------------------------------------------------------------------

/// `u = M . z` — direct matrix-vector product (NOT transposed; see this
/// module's algorithm note in the plan's `<algorithm_notes>` point 1):
/// `u[j] = M[j][0]*z[0] + M[j][1]*z[1] + M[j][2]*z[2]`.
fn matmul3(m: &[[f64; 3]; 3], z: [f64; 3]) -> [f64; 3] {
    [
        m[0][0] * z[0] + m[0][1] * z[1] + m[0][2] * z[2],
        m[1][0] * z[0] + m[1][1] * z[1] + m[1][2] * z[2],
        m[2][0] * z[0] + m[2][1] * z[1] + m[2][2] * z[2],
    ]
}

/// Layer B: nikon_c = curves[c]((raw * k) @ M)_c, clipped to [0,1]. Returns
/// the same length as `raw`. See algorithm note above for the exact matrix
/// orientation (M applied directly, not transposed).
pub fn apply(raw: &[[f64; 3]], k: [f64; 3], bundle: &Bundle) -> Vec<[f64; 3]> {
    raw.iter()
        .map(|px| {
            let z = [px[0] * k[0], px[1] * k[1], px[2] * k[2]];
            let u = matmul3(&bundle.matrix, z);
            [
                bundle.curves[0].apply(u[0]).clamp(0.0, 1.0),
                bundle.curves[1].apply(u[1]).clamp(0.0, 1.0),
                bundle.curves[2].apply(u[2]).clamp(0.0, 1.0),
            ]
        })
        .collect()
}

// ---------------------------------------------------------------------
// Tests -- ground truth generated directly from the real nikonlook_core.py
// against the real nikonlook-v1 bundle (plan 14-01's <behavior> block,
// Groups A-G). Absolute-difference tolerance of 1e-9 unless noted.
// ---------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    const EPSILON: f64 = 1e-9;

    fn assert_close(actual: f64, expected: f64, context: &str) {
        assert!(
            (actual - expected).abs() < EPSILON,
            "{context}: expected {expected}, got {actual} (diff {})",
            (actual - expected).abs()
        );
    }

    fn assert_triple_close(actual: [f64; 3], expected: [f64; 3], context: &str) {
        for c in 0..3 {
            assert_close(actual[c], expected[c], &format!("{context}[{c}]"));
        }
    }

    // Group A -- MonotoneCurve::apply on curve index 0 (R channel) -------

    #[test]
    fn group_a_monotone_curve_apply_matches_np_interp() {
        let bundle = load_bundle_v1().expect("real bundle must load");
        let curve = &bundle.curves[0];
        let cases: [(f64, f64); 7] = [
            (-0.5, 0.8745168478139992),
            (0.0, 0.8745168478139992),
            (0.1317770185749368, 0.8745168478139992),
            (0.5, 0.5160001098536164),
            (1.0, 0.16780716019028524),
            (1.7629687417420064, 0.03560082719893472),
            (2.0, 0.03560082719893472),
        ];
        for (x, expected) in cases {
            assert_close(curve.apply(x), expected, &format!("curve.apply({x})"));
        }
    }

    // Group B -- unclipped_percentiles, small-N fallback branch ----------

    #[test]
    fn group_b_unclipped_percentiles_small_n_fallback() {
        let channel = vec![
            0.01, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7,
            0.75, 0.8, 0.85, 0.9, 0.95,
        ];

        let (lo, hi) = unclipped_percentiles(&channel, 1.0, 99.0, 0.0, 1.0);
        assert_close(lo, 0.0176, "lo_pct=1,hi_pct=99 lo");
        assert_close(hi, 0.9404999999999999, "lo_pct=1,hi_pct=99 hi");

        let (lo, hi) = unclipped_percentiles(&channel, 10.0, 90.0, 0.0, 1.0);
        assert_close(lo, 0.09500000000000001, "lo_pct=10,hi_pct=90 lo");
        assert_close(hi, 0.8550000000000001, "lo_pct=10,hi_pct=90 hi");
    }

    // Group C -- unclipped_percentiles, real masking branch --------------

    #[test]
    fn group_c_unclipped_percentiles_real_masking_branch() {
        let channel: Vec<f64> = (0..1200u64)
            .map(|i| {
                let numerator = (i * 2654435761) % 1000003;
                0.02 + 0.58 * (numerator as f64 / 1000003.0)
            })
            .collect();
        let mask_count = channel
            .iter()
            .filter(|&&v| v > 0.0030518043793392844 && v < 0.99)
            .count();
        assert_eq!(
            mask_count, 1200,
            "all 1200 generated values must pass the rail mask (real masking branch, not fallback)"
        );

        let (lo, hi) =
            unclipped_percentiles(&channel, 1.0, 99.0, 0.0030518043793392844, 0.99);
        assert_close(lo, 0.026244464266607197, "group C lo");
        assert_close(hi, 0.5947020928937213, "group C hi");
    }

    // Group D -- apply() with fixed k=[1,1,1] on 5 literal raw pixels ----

    #[test]
    fn group_d_apply_fixed_gain_matches_real_bundle() {
        let bundle = load_bundle_v1().expect("real bundle must load");
        let k = [1.0, 1.0, 1.0];
        let raw: Vec<[f64; 3]> = vec![
            [0.0, 0.0, 0.0],
            [0.1, 0.1, 0.1],
            [0.2, 0.15, 0.1],
            [0.5, 0.4, 0.3],
            [1.0, 1.0, 1.0],
        ];
        let expected: [[f64; 3]; 5] = [
            [0.8745168478139992, 0.8756997585296631, 0.897667407989502],
            [0.7828965253185436, 0.38084857041171494, 0.25583754552711385],
            [0.5236465885328713, 0.192383939201308, 0.266357236552071],
            [0.09108107953023015, 0.01729307368782625, 0.04174288734793663],
            [0.03560082719893472, 0.01729307368782625, 0.04174288734793663],
        ];

        let out = apply(&raw, k, &bundle);
        for (i, (actual, expected)) in out.iter().zip(expected.iter()).enumerate() {
            assert_triple_close(*actual, *expected, &format!("group D row {i}"));
        }
    }

    // Group E -- full estimate_gains -> apply chain on a deterministic ---
    // N=24 raw grid (fallback percentile branch, N<1000)

    #[test]
    fn group_e_estimate_gains_then_apply_chain() {
        let bundle = load_bundle_v1().expect("real bundle must load");
        let raw: Vec<[f64; 3]> = (0..24u64)
            .map(|i| {
                let mut px = [0.0f64; 3];
                for c in 0..3u64 {
                    let numerator = (i * 977 + c * 131) % 997;
                    px[c as usize] = 0.02 + 0.5 * (numerator as f64 / 997.0);
                }
                px
            })
            .collect();

        // v1 ignores width/exposure entirely -- raw.len() is an arbitrary
        // but harmless stand-in width (this fixture has no real 2D shape).
        let k = estimate_gains(&raw, raw.len(), None, &bundle).expect("v1 estimate_gains never fails");
        assert_triple_close(
            k,
            [0.9317322232531161, 0.3294967219973879, 0.23854278951888058],
            "group E gains",
        );

        let out = apply(&raw, k, &bundle);
        let expectations: [(usize, [f64; 3]); 5] = [
            (0, [0.8745168478139992, 0.8571021980307203, 0.7567609770016586]),
            (1, [0.20425142067314334, 0.857088566244072, 0.7360326372205014]),
            (2, [0.21473000934038963, 0.8570978869427004, 0.7654062762850674]),
            (22, [0.36774800499631477, 0.274513254087709, 0.24570788642373684]),
            (23, [0.3876794365789769, 0.28813242852877213, 0.2539187916951131]),
        ];
        for (i, expected) in expectations {
            assert_triple_close(out[i], expected, &format!("group E row {i}"));
        }
    }

    // Group F -- load_bundle_v1() parses the real embedded v1 data --------

    #[test]
    fn group_f_load_bundle_parses_real_embedded_data() {
        let bundle = load_bundle_v1().expect("real bundle must load");
        assert_eq!(bundle.quality_tier, "beta");
        assert_eq!(bundle.bundle_version, "nikonlook-v1");

        let expected_m: [[f64; 3]; 3] = [
            [1.7824614347271908, -0.18771656838785228, 1.6621978551534453],
            [0.11056457596219628, 4.774198145017257, 0.21820331145813432],
            [0.05238546630543208, -0.37232319284521465, 6.125122811313664],
        ];
        for r in 0..3 {
            for c in 0..3 {
                assert_close(bundle.matrix[r][c], expected_m[r][c], &format!("M[{r}][{c}]"));
            }
        }

        assert_eq!(bundle.curves.len(), 3, "exactly 3 curves (R,G,B)");
        for (i, curve) in bundle.curves.iter().enumerate() {
            assert_eq!(curve.grid_x.len(), 257, "curve {i} grid_x length");
            assert_eq!(curve.grid_y.len(), 257, "curve {i} grid_y length");
        }

        let la = match &bundle.layer_a {
            LayerA::V1(la) => la,
            LayerA::V2(_) => panic!("load_bundle_v1 must produce LayerA::V1"),
        };
        assert_close(la.lo_pct, 1.0, "lo_pct");
        assert_close(la.hi_pct, 99.0, "hi_pct");
        assert_close(la.rail_lo_fraction, 0.0030518043793392844, "rail_lo_fraction");
        assert_close(la.rail_hi_fraction, 0.99, "rail_hi_fraction");
        assert_close(la.gain_bounds.0, 0.02, "gain_bounds.0");
        assert_close(la.gain_bounds.1, 100.0, "gain_bounds.1");
        assert_triple_close(
            la.reference_lo,
            [0.13874608874320984, 0.03604181110858917, 0.02080247173085809],
            "reference_lo",
        );
        assert_triple_close(
            la.reference_hi,
            [0.4708599960803984, 0.15794491887092588, 0.08893278300762175],
            "reference_hi",
        );
        assert_triple_close(
            la.reference_k,
            [1.1943464333096745, 1.3118880757884246, 1.6993638844408396],
            "reference_k",
        );
    }

    // Group G -- load_bundle() fails loudly on malformed method/model tags

    #[test]
    fn group_g_load_bundle_rejects_unsupported_layer_a_method() {
        // "hybrid-exposure-ridge-v2" was this fixture's bad-method string
        // before this port added real v2 support (Groups H-O below); it is
        // now a legitimately supported method, so this test's fixture uses
        // a still-nonexistent v3 tag to keep exercising the same
        // "unrecognized method" guard.
        let malformed_layer_a = r#"{
            "method": "hybrid-exposure-ridge-v3",
            "lo_pct": 1.0,
            "hi_pct": 99.0,
            "rail_lo_fraction": 0.003,
            "rail_hi_fraction": 0.99,
            "gain_bounds": [0.02, 100.0],
            "reference_lo": [0.1, 0.1, 0.1],
            "reference_hi": [0.5, 0.5, 0.5],
            "reference_k": [1.0, 1.0, 1.0]
        }"#;

        let result = parse_bundle(MODEL_JSON_V1, malformed_layer_a, MANIFEST_JSON_V1);
        match result {
            Ok(_) => panic!("expected Err(NikonlookError::Invalid) for unsupported Layer-A method, got Ok(_)"),
            Err(NikonlookError::Invalid(message)) => {
                assert!(
                    message.contains("hybrid-exposure-ridge-v3"),
                    "error message should name the bad method: {message}"
                );
            }
            Err(other) => panic!("expected NikonlookError::Invalid, got {other:?}"),
        }
    }

    #[test]
    fn group_g_load_bundle_rejects_unsupported_model_type() {
        // Only one "DirectPF" substring exists in model.json (the "model"
        // field itself; verified against the vendored file) so a single
        // targeted replacement is safe here.
        let malformed_model = MODEL_JSON_V1.replacen("\"DirectPF\"", "\"NotARealModel\"", 1);
        assert_ne!(malformed_model, MODEL_JSON_V1, "replacement must have changed something");

        let result = parse_bundle(&malformed_model, LAYER_A_JSON_V1, MANIFEST_JSON_V1);
        match result {
            Ok(_) => panic!("expected Err(NikonlookError::Invalid) for unsupported model type, got Ok(_)"),
            Err(NikonlookError::Invalid(message)) => {
                assert!(
                    message.contains("NotARealModel"),
                    "error message should name the bad model type: {message}"
                );
            }
            Err(other) => panic!("expected NikonlookError::Invalid, got {other:?}"),
        }
    }

    // Group H -- v2 bundle loads; v1 loader still works ---------------------

    #[test]
    fn group_h_load_bundle_v2_and_v1_both_work() {
        let v2 = load_bundle().expect("real v2 bundle must load");
        assert_eq!(v2.quality_tier, "beta");
        assert_eq!(v2.bundle_version, "nikonlook-v2");
        assert!(matches!(v2.layer_a, LayerA::V2(_)), "load_bundle() must produce LayerA::V2");

        let v1 = load_bundle_v1().expect("real v1 bundle must load");
        assert_eq!(v1.quality_tier, "beta");
        assert_eq!(v1.bundle_version, "nikonlook-v1");
        assert!(matches!(v1.layer_a, LayerA::V1(_)), "load_bundle_v1() must produce LayerA::V1");
    }

    // Group I -- v2 curve endpoints + M row0 (Layer B unchanged from v1) ---

    #[test]
    fn group_i_v2_curve_endpoints_and_matrix_row0() {
        let bundle = load_bundle().expect("real v2 bundle must load");

        assert_close(bundle.matrix[0][0], 1.7824614347271908, "M[0][0]");
        assert_close(bundle.matrix[0][1], -0.18771656838785228, "M[0][1]");
        assert_close(bundle.matrix[0][2], 1.6621978551534453, "M[0][2]");

        // (grid_x[0], grid_y[0], grid_x[last], grid_y[last]) per channel.
        let expected: [(f64, f64, f64, f64); 3] = [
            (0.1317770185749368, 0.8745168478139992, 1.7629687417420064, 0.03560082719893472),
            (0.08157912957634648, 0.8756997585296631, 1.6072961164948512, 0.01729307368782625),
            (0.06665698332439686, 0.897667407989502, 1.4779315142923606, 0.04174288734793663),
        ];
        for (i, (x0, y0, x_last, y_last)) in expected.into_iter().enumerate() {
            let curve = &bundle.curves[i];
            assert_eq!(curve.grid_x.len(), 257, "curve {i} grid_x length");
            assert_eq!(curve.grid_y.len(), 257, "curve {i} grid_y length");
            assert_close(curve.grid_x[0], x0, &format!("curve {i} grid_x[0]"));
            assert_close(curve.grid_y[0], y0, &format!("curve {i} grid_y[0]"));
            assert_close(*curve.grid_x.last().unwrap(), x_last, &format!("curve {i} grid_x[last]"));
            assert_close(*curve.grid_y.last().unwrap(), y_last, &format!("curve {i} grid_y[last]"));
        }
    }

    // Group J -- v2 exposure path: raw-independent, matches K_EXPOSURE_FRAME5

    #[test]
    fn group_j_v2_exposure_path_ignores_raw_content() {
        let bundle = load_bundle().expect("real v2 bundle must load");
        let exposure = Some([127992.0, 312892.0, 259345.0]);
        let expected = [0.5764822683598294, 0.22818411954519974, 0.2620541212542383];

        let zeros = vec![[0.0f64; 3]; 16];
        let k_zeros = estimate_gains(&zeros, 4, exposure, &bundle).expect("exposure path never fails");
        assert_triple_close(k_zeros, expected, "group J zeros");

        let other: Vec<[f64; 3]> = (0..16u64).map(|i| [i as f64 * 0.01, 0.5, 0.9]).collect();
        let k_other = estimate_gains(&other, 4, exposure, &bundle).expect("exposure path never fails");
        assert_triple_close(k_other, expected, "group J other raw");
        assert_eq!(k_zeros, k_other, "exposure path gain must be independent of raw content");
    }

    // Group K -- v2 blind features + gains on synthetic SMALL/LARGE images -

    /// pixel[y][x][c] = 0.001 + (((y*31 + x*17 + c*7) % 997) / 996.0) * 0.979
    fn synthetic_pixel(y: usize, x: usize, c: usize) -> f64 {
        0.001 + (((y * 31 + x * 17 + c * 7) % 997) as f64 / 996.0) * 0.979
    }

    /// `height` rows x `width` columns, row-major -- NOTE: "SMALL 64x48" /
    /// "LARGE 640x528" in the spec these literals come from are HEIGHT x
    /// WIDTH, not the conventional WIDTH x HEIGHT: verified numerically
    /// against the real nikonlook_core.py (the ground-truth feature/gain
    /// literals below only match with height first).
    fn synthetic_image(height: usize, width: usize) -> Vec<[f64; 3]> {
        let mut out = Vec::with_capacity(height * width);
        for y in 0..height {
            for x in 0..width {
                out.push([
                    synthetic_pixel(y, x, 0),
                    synthetic_pixel(y, x, 1),
                    synthetic_pixel(y, x, 2),
                ]);
            }
        }
        out
    }

    const FEATURES_SMALL: [f64; 48] = [
        -5.276819193487845, -4.686672123817594, -3.837691664648756, -3.248230707139783,
        -2.438388715206751, -1.318186352226604, -0.7213886280029097, -0.6319817175451528,
        -0.34541783222928263, -0.2805077357919461, -0.15668763010574904, -0.07512298200466797,
        -0.049349043204796404, -0.05473058381684684, -0.08510909109773852, -0.18220818972626776,
        -5.653143761930368, -5.509757581497301, -5.172755649597922, -4.4554008631084,
        -3.074453899755448, -1.4384436548288964, -0.9600624477992327, -0.6896441866673314,
        -0.6132045705744212, -0.30607522765713757, -0.27434602600439156, -0.2722144966158421,
        -0.2715049952737915, -0.2761158860804166, -0.27754195749601346, -0.2818324145748725,
        -4.567200448058146, -4.51646262450441, -4.378078615076415, -3.990190798492968,
        -2.9356653314264762, -1.4098606403903666, -0.9422510590708205, -0.6760244343484456,
        -0.6005808126806663, -0.2967742856494665, -0.26533425788426007, -0.2632218308676478,
        -0.2625186789992431, -0.27611588608041676, -0.27754195749601357, -0.2818324145748727,
    ];
    const K_BLIND_SMALL: [f64; 3] = [0.759056869674804, 0.4991515696181712, 0.25250512923880397];

    const FEATURES_LARGE: [f64; 48] = [
        -4.27544253055643, -3.6950615763223453, -2.942165811758224, -2.277533058276149,
        -1.6087283248934678, -1.0556249293998055, -0.7113285324721654, -0.44881830605817313,
        -0.2410877258810704, -0.12289021930166683, -0.07059807479936706, -0.039709348178583556,
        -0.029270620878216348, -0.04369306952750571, -0.06590178463114499, -0.12887369659697004,
        -4.525498260669563, -3.865448911299333, -2.9782109692314354, -2.3096784646676807,
        -1.6265667079680415, -1.064135199834472, -0.7103280669014537, -0.45298422422682316,
        -0.24409442795786648, -0.12533842605280804, -0.07138951265305483, -0.04251561329152198,
        -0.03144906708465092, -0.042687281027757464, -0.06462173745135834, -0.12758867253545841,
        -4.358686684976851, -3.8645111488618937, -2.9393747157889125, -2.2900733311052863,
        -1.625567294363984, -1.0652753943733737, -0.708330133556367, -0.44889529518414606,
        -0.24434539500905586, -0.1254498507174158, -0.07144229745436559, -0.04181843290186852,
        -0.030445379070405683, -0.04372387493488411, -0.06392993527918077, -0.1299364851182066,
    ];
    const K_BLIND_LARGE: [f64; 3] = [0.702656406701031, 0.43156628045481704, 0.21943355626290767];

    #[test]
    fn group_k_v2_blind_features_and_gains_small_and_large() {
        let bundle = load_bundle().expect("real v2 bundle must load");
        let blind = match &bundle.layer_a {
            LayerA::V2(la) => &la.blind,
            LayerA::V1(_) => panic!("load_bundle must produce LayerA::V2"),
        };

        // SMALL: 64 tall x 48 wide -- 4*3=12 samples/channel at stride 16,
        // under 1000, exercises the unmasked fallback branch.
        let small = synthetic_image(64, 48);
        let features_small = layer_a_v2_features(&small, 48, blind).expect("feature extraction must succeed");
        for i in 0..48 {
            assert_close(features_small[i], FEATURES_SMALL[i], &format!("FEATURES_SMALL[{i}]"));
        }
        let k_small = estimate_gains(&small, 48, None, &bundle).expect("blind path never fails on real data");
        assert_triple_close(k_small, K_BLIND_SMALL, "K_BLIND_SMALL");

        // LARGE: 640 tall x 528 wide -- 40*33=1320 samples/channel at
        // stride 16, at/above 1000, exercises the rail-mask branch.
        let large = synthetic_image(640, 528);
        let features_large = layer_a_v2_features(&large, 528, blind).expect("feature extraction must succeed");
        for i in 0..48 {
            assert_close(features_large[i], FEATURES_LARGE[i], &format!("FEATURES_LARGE[{i}]"));
        }
        let k_large = estimate_gains(&large, 528, None, &bundle).expect("blind path never fails on real data");
        assert_triple_close(k_large, K_BLIND_LARGE, "K_BLIND_LARGE");
    }

    // Group L -- apply() probe with the v2 bundle (Layer B is unchanged) ---

    #[test]
    fn group_l_v2_apply_probe() {
        let bundle = load_bundle().expect("real v2 bundle must load");
        let k = [0.7, 0.35, 0.28];
        let raw: Vec<[f64; 3]> = vec![
            [0.01, 0.012, 0.009],
            [0.1, 0.08, 0.06],
            [0.3, 0.25, 0.2],
            [0.455, 0.462, 0.364],
            [0.7, 0.65, 0.6],
            [0.95, 0.93, 0.9],
        ];
        let expected: [[f64; 3]; 6] = [
            [0.8745168478139992, 0.8756997585296631, 0.897667407989502],
            [0.8745168180192864, 0.8571021416704295, 0.8712481287405098],
            [0.5952691635855909, 0.43141306059503676, 0.5400840883143807],
            [0.31321822693219087, 0.16022528207334077, 0.2557434375355004],
            [0.13062594216570117, 0.05440001030661233, 0.10826353557346319],
            [0.061124366591036455, 0.01729307368782625, 0.04543075730736556],
        ];

        let out = apply(&raw, k, &bundle);
        for (i, (actual, expected)) in out.iter().zip(expected.iter()).enumerate() {
            assert_triple_close(*actual, *expected, &format!("group L row {i}"));
        }
    }

    // Group M -- regression: blind gains on LARGE stay level-appropriate ---

    #[test]
    fn group_m_v2_blind_large_regression_and_pin_fraction() {
        let bundle = load_bundle().expect("real v2 bundle must load");
        let large = synthetic_image(640, 528);
        let k = estimate_gains(&large, 528, None, &bundle).expect("blind path never fails on real data");
        assert_triple_close(k, K_BLIND_LARGE, "K_BLIND_LARGE (regression)");

        let out = apply(&large, k, &bundle);
        // v1 would be a poor comparison on synthetic data -- the real
        // regression proof lives in the env-gated fixture test
        // (tests/nikonlook_v2_fixture.rs) against a real archive + Nikon
        // reference. This is a loose sanity bound only.
        for c in 0..3 {
            let grid_y0 = bundle.curves[c].grid_y[0];
            let pinned = out.iter().filter(|px| px[c] == grid_y0).count();
            let fraction = pinned as f64 / out.len() as f64;
            assert!(
                fraction < 0.5,
                "channel {c}: {fraction} of output pixels pinned at grid_y[0] ({grid_y0}), expected < 0.5"
            );
        }
    }

    // Group N -- v2 exposure invariance: gain scales exactly inversely -----

    #[test]
    fn group_n_v2_exposure_invariance_under_uniform_scaling() {
        let bundle = load_bundle().expect("real v2 bundle must load");
        let large = synthetic_image(640, 528);
        let exposure = [127992.0, 312892.0, 259345.0];
        let e = 2.0;
        let exposure_scaled = exposure.map(|value| value * e);

        let k1 = estimate_gains(&large, 528, Some(exposure), &bundle).expect("exposure path never fails");
        let k2 = estimate_gains(&large, 528, Some(exposure_scaled), &bundle).expect("exposure path never fails");

        let large_scaled: Vec<[f64; 3]> =
            large.iter().map(|px| [px[0] * e, px[1] * e, px[2] * e]).collect();

        let out1 = apply(&large, k1, &bundle);
        let out2 = apply(&large_scaled, k2, &bundle);
        for (i, (a, b)) in out1.iter().zip(out2.iter()).enumerate() {
            assert_triple_close(*a, *b, &format!("group N pixel {i}"));
        }
    }

    // Group O -- v2 validation failures (Group-G style, tamper one field) --

    /// A minimal, otherwise-valid v2 layer_a.json fixture, so each test
    /// below tampers exactly one field via a single targeted string
    /// replacement -- mirrors Group G's `.replacen(...)` style.
    /// `feature_mean_len` lets the length-mismatch test build a
    /// structurally different array without a second bespoke literal.
    fn minimal_v2_layer_a_json(feature_mean_len: usize) -> String {
        let feature_mean = vec!["0.0".to_string(); feature_mean_len].join(", ");
        let feature_scale = vec!["1.0".to_string(); LAYER_A_V2_FEATURE_COUNT].join(", ");
        let coefficients = vec!["[0.01, 0.02, 0.03]".to_string(); LAYER_A_V2_FEATURE_COUNT].join(", ");
        format!(
            r#"{{
                "method": "hybrid-exposure-ridge-v2",
                "metadata_estimator": {{
                    "method": "inverse-hardware-exposure-v1",
                    "reference_exposure_10ns": [10.0, 20.0, 30.0],
                    "reference_gain": [1.0, 1.0, 1.0],
                    "gain_bounds": [0.02, 100.0]
                }},
                "blind_fallback": {{
                    "method": "log-ridge-raw-features-v1",
                    "feature_schema": "raw-rail-quantiles-log-v1",
                    "sample_stride": 16,
                    "rail_lo_fraction": 0.003,
                    "rail_hi_fraction": 0.99,
                    "gain_bounds": [0.02, 100.0],
                    "feature_mean": [{feature_mean}],
                    "feature_scale": [{feature_scale}],
                    "log_gain_intercept": [0.0, 0.0, 0.0],
                    "coefficients": [{coefficients}]
                }}
            }}"#
        )
    }

    fn assert_v2_fixture_invalid(json: &str, needle: &str) {
        match parse_bundle(MODEL_JSON_V2, json, MANIFEST_JSON_V2) {
            Ok(_) => panic!("expected Err(NikonlookError::Invalid) naming {needle:?}, got Ok(_)"),
            Err(NikonlookError::Invalid(message)) => {
                assert!(
                    message.contains(needle),
                    "expected message to contain {needle:?}, got {message:?}"
                );
            }
            Err(other) => panic!("expected NikonlookError::Invalid, got {other:?}"),
        }
    }

    #[test]
    fn group_o_minimal_v2_fixture_is_actually_valid() {
        // Sanity check for the tamper tests below: the untampered baseline
        // must load, or a "tamper" test could be passing for the wrong
        // reason (a baseline that was already broken).
        parse_bundle(MODEL_JSON_V2, &minimal_v2_layer_a_json(LAYER_A_V2_FEATURE_COUNT), MANIFEST_JSON_V2)
            .expect("untampered minimal v2 fixture must load");
    }

    #[test]
    fn group_o_rejects_wrong_metadata_method_string() {
        let json = minimal_v2_layer_a_json(LAYER_A_V2_FEATURE_COUNT)
            .replacen("\"inverse-hardware-exposure-v1\"", "\"wrong-method-v9\"", 1);
        assert_v2_fixture_invalid(&json, "wrong-method-v9");
    }

    #[test]
    fn group_o_rejects_47_length_feature_mean() {
        let json = minimal_v2_layer_a_json(LAYER_A_V2_FEATURE_COUNT - 1);
        assert_v2_fixture_invalid(&json, "feature_mean");
    }

    #[test]
    fn group_o_rejects_coefficients_row_length_2() {
        let json = minimal_v2_layer_a_json(LAYER_A_V2_FEATURE_COUNT)
            .replacen("[0.01, 0.02, 0.03]", "[0.01, 0.02]", 1);
        assert_v2_fixture_invalid(&json, "coefficients");
    }

    #[test]
    fn group_o_rejects_stride_zero() {
        let json = minimal_v2_layer_a_json(LAYER_A_V2_FEATURE_COUNT)
            .replacen("\"sample_stride\": 16", "\"sample_stride\": 0", 1);
        assert_v2_fixture_invalid(&json, "sample_stride");
    }

    #[test]
    fn group_o_rejects_non_positive_reference_gain() {
        let json = minimal_v2_layer_a_json(LAYER_A_V2_FEATURE_COUNT)
            .replacen("\"reference_gain\": [1.0, 1.0, 1.0]", "\"reference_gain\": [1.0, -1.0, 1.0]", 1);
        assert_v2_fixture_invalid(&json, "reference_gain");
    }
}
