//! Rust port of `negfit/nikonlook_core.py`'s frozen bundle API
//! (`load_bundle` / `estimate_gains` / `apply`) — the "Nikon Scan look"
//! color pipeline: a shared 3x3 matrix + per-channel monotone curve model
//! (Layer B) plus a blind per-frame exposure gain estimator (Layer A,
//! `percentile-stopgap-v1` only — `load_bundle` rejects any other Layer A
//! method or Layer B model type instead of silently applying wrong math).
//!
//! The `nikonlook-v1` bundle's JSON matrices/curves are vendored as
//! compiled-in engine resources under `engine/resources/nikonlook-v1/`
//! and embedded via `include_str!` — no runtime file path, no network
//! access. The numeric model targets Adobe RGB-family encoded values, but
//! ScanStudio does not redistribute or embed a Nikon ICC profile. See
//! `engine/resources/nikonlook-v1/PROVENANCE.md` for the vendoring record
//! and the owner's licensing grant citation.
//!
//! Every numeric literal in this module's test suite (Groups A-G) was
//! generated by directly invoking the real `nikonlook_core.py` against the
//! real `nikonlook-v1` bundle (see plan 14-01's `<behavior>` block) — this
//! is a faithful numeric port of a verified reference implementation, not a
//! reimplementation from first principles.

use serde::Deserialize;

// ---------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------

/// Mirrors `app/ScanStudio/engine/src/parity/types.rs`'s `ParityError`
/// shape. No `Io` variant — this module never touches the filesystem at
/// runtime (bundle data is compiled in via `include_str!`).
#[derive(Debug)]
pub enum NikonlookError {
    Json(serde_json::Error),
    Invalid(String),
}

impl std::fmt::Display for NikonlookError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            NikonlookError::Json(err) => write!(f, "json error: {err}"),
            NikonlookError::Invalid(message) => write!(f, "invalid nikonlook bundle: {message}"),
        }
    }
}

impl std::error::Error for NikonlookError {}

impl From<serde_json::Error> for NikonlookError {
    fn from(err: serde_json::Error) -> Self {
        NikonlookError::Json(err)
    }
}

// ---------------------------------------------------------------------
// MonotoneCurve
// ---------------------------------------------------------------------

/// One Layer-B monotone curve (R, G, or B). `.apply(x)` must match NumPy's
/// `np.interp(x, grid_x, grid_y)` exactly: grid_x is sorted ascending
/// (verified: 257 points in the nikonlook-v1 bundle, strictly increasing).
/// If x <= grid_x[0], return grid_y[0]. If x >= grid_x[last], return
/// grid_y[last]. Otherwise linearly interpolate between the two bracketing
/// grid points. (`decreasing` from the Python source is provenance-only and
/// is never read by `.apply()` — confirmed by reading nikonlook_core.py's
/// `MonotoneCurveLite.apply`, which always does `np.interp(x, grid_x,
/// grid_y)` regardless of the `decreasing` flag — so this port omits the
/// field from this struct entirely.)
pub struct MonotoneCurve {
    pub grid_x: Vec<f64>,
    pub grid_y: Vec<f64>,
}

impl MonotoneCurve {
    pub fn apply(&self, x: f64) -> f64 {
        let n = self.grid_x.len();
        debug_assert!(n > 0, "MonotoneCurve grid must be non-empty");
        if n == 1 {
            return self.grid_y[0];
        }
        if x <= self.grid_x[0] {
            return self.grid_y[0];
        }
        if x >= self.grid_x[n - 1] {
            return self.grid_y[n - 1];
        }
        // First index where grid_x[i] > x. Since grid_x is strictly
        // ascending and grid_x[0] < x < grid_x[n-1] here, `hi` is in
        // 1..=(n-1) — matches NumPy's np.interp bracketing for a strictly
        // increasing grid, including the exact-grid-point case (frac = 0).
        let hi = self.grid_x.partition_point(|&gx| gx <= x);
        let lo = hi - 1;
        let x0 = self.grid_x[lo];
        let x1 = self.grid_x[hi];
        let y0 = self.grid_y[lo];
        let y1 = self.grid_y[hi];
        let span = x1 - x0;
        if span <= 0.0 {
            // Degenerate/duplicate grid_x — not expected in the real
            // bundle (verified strictly increasing), but np.interp
            // returns the right-hand sample in this case.
            return y1;
        }
        let frac = (x - x0) / span;
        y0 + (y1 - y0) * frac
    }
}

// ---------------------------------------------------------------------
// Bundle
// ---------------------------------------------------------------------

/// A loaded nikonlook bundle. Fields are private — only load_bundle /
/// estimate_gains / apply (this module's frozen API surface) touch them.
/// quality_tier/bundle_version are exposed for future provenance/debug/UI
/// use even though nothing calls them yet in this phase.
pub struct Bundle {
    matrix: [[f64; 3]; 3], // "M" from model.json, applied as-is (not transposed) — see algorithm note below
    curves: [MonotoneCurve; 3], // R, G, B order, from model.json's "curves"
    layer_a: LayerAV1,
    pub quality_tier: String,   // manifest.json "quality_tier"
    pub bundle_version: String, // manifest.json "bundle_version"
}

struct LayerAV1 {
    lo_pct: f64,
    hi_pct: f64,
    rail_lo_fraction: f64,
    rail_hi_fraction: f64,
    reference_lo: [f64; 3],
    reference_hi: [f64; 3],
    reference_k: [f64; 3],
    gain_bounds: (f64, f64),
}

// ---------------------------------------------------------------------
// Deserialization DTOs — only the fields this module actually reads.
// serde ignores the many other fields present in the real JSON
// automatically since none of these DTOs sets `deny_unknown_fields`.
// ---------------------------------------------------------------------

#[derive(Deserialize)]
struct ModelDto {
    model: String,
    #[serde(rename = "M")]
    m: Vec<Vec<f64>>,
    curves: Vec<CurveDto>,
}

#[derive(Deserialize)]
struct CurveDto {
    grid_x: Vec<f64>,
    grid_y: Vec<f64>,
    // Provenance-only in the Python source (see MonotoneCurve's doc
    // comment above) — deserialized to mirror the on-disk shape 1:1 but
    // deliberately never read past that.
    #[allow(dead_code)]
    decreasing: bool,
}

#[derive(Deserialize)]
struct LayerADto {
    method: String,
    lo_pct: f64,
    hi_pct: f64,
    rail_lo_fraction: f64,
    rail_hi_fraction: f64,
    gain_bounds: Vec<f64>,
    reference_lo: Vec<f64>,
    reference_hi: Vec<f64>,
    reference_k: Vec<f64>,
}

#[derive(Deserialize)]
struct ManifestDto {
    bundle_version: String,
    quality_tier: String,
    layer_a_method: Option<String>,
}

// ---------------------------------------------------------------------
// Embedded bundle data — hermetic, no runtime file path, no network.
// ---------------------------------------------------------------------

const MODEL_JSON: &str = include_str!("../../resources/nikonlook-v1/model.json");
const LAYER_A_JSON: &str = include_str!("../../resources/nikonlook-v1/layer_a.json");
const MANIFEST_JSON: &str = include_str!("../../resources/nikonlook-v1/manifest.json");

/// Parses the three embedded JSON strings (model.json, layer_a.json,
/// manifest.json) via include_str!. No file path parameter — this port only
/// ever loads the one vendored numeric bundle. Returns
/// NikonlookError::Invalid (not a panic) if
/// model.json's "model" field != "DirectPF", or layer_a.json's "method"
/// field != "percentile-stopgap-v1" (this port implements ONLY the v1
/// percentile-stopgap method — the only method the nikonlook-v1 bundle
/// uses; any other method fails loudly here, exactly mirroring
/// nikonlook_core.py's own _validate_layer_a/estimate_gains guard behavior
/// for unsupported methods, never silently applying wrong math).
pub fn load_bundle() -> Result<Bundle, NikonlookError> {
    parse_bundle(MODEL_JSON, LAYER_A_JSON, MANIFEST_JSON)
}

/// Internal parse/validate helper shared by `load_bundle` (real embedded
/// data) and this module's own tests (hand-built malformed JSON strings) —
/// see the Group G tests below.
fn parse_bundle(
    model_json: &str,
    layer_a_json: &str,
    manifest_json: &str,
) -> Result<Bundle, NikonlookError> {
    let model: ModelDto = serde_json::from_str(model_json)?;
    let layer_a: LayerADto = serde_json::from_str(layer_a_json)?;
    let manifest: ManifestDto = serde_json::from_str(manifest_json)?;

    if model.model != "DirectPF" {
        return Err(NikonlookError::Invalid(format!(
            "model.json: unrecognized Layer B model type {:?} — this port only applies \
             DirectPF-format models (fit37/model_directpf.py's serialization)",
            model.model
        )));
    }
    if layer_a.method != "percentile-stopgap-v1" {
        return Err(NikonlookError::Invalid(format!(
            "layer_a.json: unsupported Layer-A method {:?} — this port implements only \
             percentile-stopgap-v1",
            layer_a.method
        )));
    }
    if let Some(manifest_method) = &manifest.layer_a_method {
        if manifest_method != &layer_a.method {
            return Err(NikonlookError::Invalid(format!(
                "manifest layer_a_method {manifest_method:?} does not match layer_a.json \
                 method {:?}",
                layer_a.method
            )));
        }
    }

    if model.m.len() != 3 || !model.m.iter().all(|row| row.len() == 3) {
        return Err(NikonlookError::Invalid(format!(
            "model.json: expected a 3x3 'M' matrix, got {} row(s)",
            model.m.len()
        )));
    }
    let mut matrix = [[0.0f64; 3]; 3];
    for (i, row) in model.m.iter().enumerate() {
        matrix[i] = [row[0], row[1], row[2]];
    }

    if model.curves.len() != 3 {
        return Err(NikonlookError::Invalid(format!(
            "model.json: expected exactly 3 curves (R,G,B), got {}",
            model.curves.len()
        )));
    }
    let curves_vec: Vec<MonotoneCurve> = model
        .curves
        .into_iter()
        .map(|curve| MonotoneCurve {
            grid_x: curve.grid_x,
            grid_y: curve.grid_y,
        })
        .collect();
    let curves: [MonotoneCurve; 3] = curves_vec
        .try_into()
        .map_err(|_| NikonlookError::Invalid("model.json: expected exactly 3 curves (R,G,B)".to_string()))?;

    let reference_lo = fixed3(&layer_a.reference_lo, "layer_a.json:reference_lo")?;
    let reference_hi = fixed3(&layer_a.reference_hi, "layer_a.json:reference_hi")?;
    let reference_k = fixed3(&layer_a.reference_k, "layer_a.json:reference_k")?;
    let gain_bounds = fixed2(&layer_a.gain_bounds, "layer_a.json:gain_bounds")?;

    let layer_a_v1 = LayerAV1 {
        lo_pct: layer_a.lo_pct,
        hi_pct: layer_a.hi_pct,
        rail_lo_fraction: layer_a.rail_lo_fraction,
        rail_hi_fraction: layer_a.rail_hi_fraction,
        reference_lo,
        reference_hi,
        reference_k,
        gain_bounds: (gain_bounds[0], gain_bounds[1]),
    };

    Ok(Bundle {
        matrix,
        curves,
        layer_a: layer_a_v1,
        quality_tier: manifest.quality_tier,
        bundle_version: manifest.bundle_version,
    })
}

/// Validates a field's value slice has exactly 3 elements, converting into
/// a fixed-size array — `NikonlookError::Invalid` with a clear message
/// (naming the field) on any shape mismatch.
fn fixed3(values: &[f64], field: &str) -> Result<[f64; 3], NikonlookError> {
    if values.len() != 3 {
        return Err(NikonlookError::Invalid(format!(
            "{field}: expected 3 values, got {}",
            values.len()
        )));
    }
    Ok([values[0], values[1], values[2]])
}

/// Same as `fixed3` but for 2-element fields (e.g. `gain_bounds`).
fn fixed2(values: &[f64], field: &str) -> Result<[f64; 2], NikonlookError> {
    if values.len() != 2 {
        return Err(NikonlookError::Invalid(format!(
            "{field}: expected 2 values, got {}",
            values.len()
        )));
    }
    Ok([values[0], values[1]])
}

// ---------------------------------------------------------------------
// Percentile primitive (mirrors nikonlook_core.py's unclipped_percentiles)
// ---------------------------------------------------------------------

/// NumPy's default "linear" percentile interpolation on an ALREADY SORTED
/// ascending slice. `p` is in [0, 100].
fn percentile_linear(sorted: &[f64], p: f64) -> f64 {
    let n = sorted.len();
    debug_assert!(n > 0, "percentile_linear requires a non-empty slice");
    if n == 1 {
        return sorted[0];
    }
    let idx = (p / 100.0) * (n - 1) as f64;
    let lo_idx = idx.floor() as usize;
    let hi_idx = idx.ceil() as usize;
    if lo_idx == hi_idx {
        return sorted[lo_idx];
    }
    let frac = idx - lo_idx as f64;
    sorted[lo_idx] * (1.0 - frac) + sorted[hi_idx] * frac
}

/// Per-channel [lo_pct, hi_pct] percentile of a single-channel raw-linear
/// slice, excluding samples at/near the sensor rails (<= rail_lo_fraction
/// or >= rail_hi_fraction), so a handful of blown highlights or a
/// near-black border don't skew the anchor points. Falls back to the
/// unmasked population if fewer than 1000 unclipped samples remain (uses
/// the ENTIRE original slice in that case, not the small filtered subset).
fn unclipped_percentiles(
    channel: &[f64],
    lo_pct: f64,
    hi_pct: f64,
    rail_lo_fraction: f64,
    rail_hi_fraction: f64,
) -> (f64, f64) {
    let masked: Vec<f64> = channel
        .iter()
        .copied()
        .filter(|&v| v > rail_lo_fraction && v < rail_hi_fraction)
        .collect();
    let mut vals = if masked.len() >= 1000 { masked } else { channel.to_vec() };
    // f64::total_cmp, not partial_cmp().unwrap(), so a stray NaN cannot
    // panic the sort.
    vals.sort_by(f64::total_cmp);
    let lo = percentile_linear(&vals, lo_pct);
    let hi = percentile_linear(&vals, hi_pct);
    (lo, hi)
}

// ---------------------------------------------------------------------
// Layer A -- estimate_gains (percentile-stopgap-v1 only)
// ---------------------------------------------------------------------

/// Per-frame exposure gain estimate ("Layer A", percentile-stopgap-v1 only
/// — see load_bundle's method guard). `raw` is scanner-linear RGB in
/// [0,1] (16-bit raw counts / 65535), one [R,G,B] triple per pixel,
/// row-major, any length. Returns (3,) gain, clamped to
/// bundle.layer_a.gain_bounds. Omits the `meta` parameter present in
/// nikonlook_core.py's signature: v1 ignores meta unconditionally per the
/// frozen API's own documented behavior, and load_bundle rejects any
/// non-v1 method before this function could ever need it.
pub fn estimate_gains(raw: &[[f64; 3]], bundle: &Bundle) -> [f64; 3] {
    let la = &bundle.layer_a;
    let mut k = [0.0f64; 3];
    for c in 0..3 {
        let channel: Vec<f64> = raw.iter().map(|px| px[c]).collect();
        let (in_lo, in_hi) = unclipped_percentiles(
            &channel,
            la.lo_pct,
            la.hi_pct,
            la.rail_lo_fraction,
            la.rail_hi_fraction,
        );
        let in_span = (in_hi - in_lo).max(1e-9);
        let ref_span = (la.reference_hi[c] - la.reference_lo[c]).max(1e-9);
        k[c] = la.reference_k[c] * (ref_span / in_span);
    }
    let (lo_bound, hi_bound) = la.gain_bounds;
    for value in k.iter_mut() {
        *value = value.clamp(lo_bound, hi_bound);
    }
    k
}

// ---------------------------------------------------------------------
// Layer B -- apply
// ---------------------------------------------------------------------

/// `u = M . z` — direct matrix-vector product (NOT transposed; see this
/// module's algorithm note in the plan's `<algorithm_notes>` point 1):
/// `u[j] = M[j][0]*z[0] + M[j][1]*z[1] + M[j][2]*z[2]`.
fn matmul3(m: &[[f64; 3]; 3], z: [f64; 3]) -> [f64; 3] {
    [
        m[0][0] * z[0] + m[0][1] * z[1] + m[0][2] * z[2],
        m[1][0] * z[0] + m[1][1] * z[1] + m[1][2] * z[2],
        m[2][0] * z[0] + m[2][1] * z[1] + m[2][2] * z[2],
    ]
}

/// Layer B: nikon_c = curves[c]((raw * k) @ M)_c, clipped to [0,1]. Returns
/// the same length as `raw`. See algorithm note above for the exact matrix
/// orientation (M applied directly, not transposed).
pub fn apply(raw: &[[f64; 3]], k: [f64; 3], bundle: &Bundle) -> Vec<[f64; 3]> {
    raw.iter()
        .map(|px| {
            let z = [px[0] * k[0], px[1] * k[1], px[2] * k[2]];
            let u = matmul3(&bundle.matrix, z);
            [
                bundle.curves[0].apply(u[0]).clamp(0.0, 1.0),
                bundle.curves[1].apply(u[1]).clamp(0.0, 1.0),
                bundle.curves[2].apply(u[2]).clamp(0.0, 1.0),
            ]
        })
        .collect()
}

// ---------------------------------------------------------------------
// Tests -- ground truth generated directly from the real nikonlook_core.py
// against the real nikonlook-v1 bundle (plan 14-01's <behavior> block,
// Groups A-G). Absolute-difference tolerance of 1e-9 unless noted.
// ---------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    const EPSILON: f64 = 1e-9;

    fn assert_close(actual: f64, expected: f64, context: &str) {
        assert!(
            (actual - expected).abs() < EPSILON,
            "{context}: expected {expected}, got {actual} (diff {})",
            (actual - expected).abs()
        );
    }

    fn assert_triple_close(actual: [f64; 3], expected: [f64; 3], context: &str) {
        for c in 0..3 {
            assert_close(actual[c], expected[c], &format!("{context}[{c}]"));
        }
    }

    // Group A -- MonotoneCurve::apply on curve index 0 (R channel) -------

    #[test]
    fn group_a_monotone_curve_apply_matches_np_interp() {
        let bundle = load_bundle().expect("real bundle must load");
        let curve = &bundle.curves[0];
        let cases: [(f64, f64); 7] = [
            (-0.5, 0.8745168478139992),
            (0.0, 0.8745168478139992),
            (0.1317770185749368, 0.8745168478139992),
            (0.5, 0.5160001098536164),
            (1.0, 0.16780716019028524),
            (1.7629687417420064, 0.03560082719893472),
            (2.0, 0.03560082719893472),
        ];
        for (x, expected) in cases {
            assert_close(curve.apply(x), expected, &format!("curve.apply({x})"));
        }
    }

    // Group B -- unclipped_percentiles, small-N fallback branch ----------

    #[test]
    fn group_b_unclipped_percentiles_small_n_fallback() {
        let channel = vec![
            0.01, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7,
            0.75, 0.8, 0.85, 0.9, 0.95,
        ];

        let (lo, hi) = unclipped_percentiles(&channel, 1.0, 99.0, 0.0, 1.0);
        assert_close(lo, 0.0176, "lo_pct=1,hi_pct=99 lo");
        assert_close(hi, 0.9404999999999999, "lo_pct=1,hi_pct=99 hi");

        let (lo, hi) = unclipped_percentiles(&channel, 10.0, 90.0, 0.0, 1.0);
        assert_close(lo, 0.09500000000000001, "lo_pct=10,hi_pct=90 lo");
        assert_close(hi, 0.8550000000000001, "lo_pct=10,hi_pct=90 hi");
    }

    // Group C -- unclipped_percentiles, real masking branch --------------

    #[test]
    fn group_c_unclipped_percentiles_real_masking_branch() {
        let channel: Vec<f64> = (0..1200u64)
            .map(|i| {
                let numerator = (i * 2654435761) % 1000003;
                0.02 + 0.58 * (numerator as f64 / 1000003.0)
            })
            .collect();
        let mask_count = channel
            .iter()
            .filter(|&&v| v > 0.0030518043793392844 && v < 0.99)
            .count();
        assert_eq!(
            mask_count, 1200,
            "all 1200 generated values must pass the rail mask (real masking branch, not fallback)"
        );

        let (lo, hi) =
            unclipped_percentiles(&channel, 1.0, 99.0, 0.0030518043793392844, 0.99);
        assert_close(lo, 0.026244464266607197, "group C lo");
        assert_close(hi, 0.5947020928937213, "group C hi");
    }

    // Group D -- apply() with fixed k=[1,1,1] on 5 literal raw pixels ----

    #[test]
    fn group_d_apply_fixed_gain_matches_real_bundle() {
        let bundle = load_bundle().expect("real bundle must load");
        let k = [1.0, 1.0, 1.0];
        let raw: Vec<[f64; 3]> = vec![
            [0.0, 0.0, 0.0],
            [0.1, 0.1, 0.1],
            [0.2, 0.15, 0.1],
            [0.5, 0.4, 0.3],
            [1.0, 1.0, 1.0],
        ];
        let expected: [[f64; 3]; 5] = [
            [0.8745168478139992, 0.8756997585296631, 0.897667407989502],
            [0.7828965253185436, 0.38084857041171494, 0.25583754552711385],
            [0.5236465885328713, 0.192383939201308, 0.266357236552071],
            [0.09108107953023015, 0.01729307368782625, 0.04174288734793663],
            [0.03560082719893472, 0.01729307368782625, 0.04174288734793663],
        ];

        let out = apply(&raw, k, &bundle);
        for (i, (actual, expected)) in out.iter().zip(expected.iter()).enumerate() {
            assert_triple_close(*actual, *expected, &format!("group D row {i}"));
        }
    }

    // Group E -- full estimate_gains -> apply chain on a deterministic ---
    // N=24 raw grid (fallback percentile branch, N<1000)

    #[test]
    fn group_e_estimate_gains_then_apply_chain() {
        let bundle = load_bundle().expect("real bundle must load");
        let raw: Vec<[f64; 3]> = (0..24u64)
            .map(|i| {
                let mut px = [0.0f64; 3];
                for c in 0..3u64 {
                    let numerator = (i * 977 + c * 131) % 997;
                    px[c as usize] = 0.02 + 0.5 * (numerator as f64 / 997.0);
                }
                px
            })
            .collect();

        let k = estimate_gains(&raw, &bundle);
        assert_triple_close(
            k,
            [0.9317322232531161, 0.3294967219973879, 0.23854278951888058],
            "group E gains",
        );

        let out = apply(&raw, k, &bundle);
        let expectations: [(usize, [f64; 3]); 5] = [
            (0, [0.8745168478139992, 0.8571021980307203, 0.7567609770016586]),
            (1, [0.20425142067314334, 0.857088566244072, 0.7360326372205014]),
            (2, [0.21473000934038963, 0.8570978869427004, 0.7654062762850674]),
            (22, [0.36774800499631477, 0.274513254087709, 0.24570788642373684]),
            (23, [0.3876794365789769, 0.28813242852877213, 0.2539187916951131]),
        ];
        for (i, expected) in expectations {
            assert_triple_close(out[i], expected, &format!("group E row {i}"));
        }
    }

    // Group F -- load_bundle() parses the real embedded data correctly ---

    #[test]
    fn group_f_load_bundle_parses_real_embedded_data() {
        let bundle = load_bundle().expect("real bundle must load");
        assert_eq!(bundle.quality_tier, "beta");
        assert_eq!(bundle.bundle_version, "nikonlook-v1");

        let expected_m: [[f64; 3]; 3] = [
            [1.7824614347271908, -0.18771656838785228, 1.6621978551534453],
            [0.11056457596219628, 4.774198145017257, 0.21820331145813432],
            [0.05238546630543208, -0.37232319284521465, 6.125122811313664],
        ];
        for r in 0..3 {
            for c in 0..3 {
                assert_close(bundle.matrix[r][c], expected_m[r][c], &format!("M[{r}][{c}]"));
            }
        }

        assert_eq!(bundle.curves.len(), 3, "exactly 3 curves (R,G,B)");
        for (i, curve) in bundle.curves.iter().enumerate() {
            assert_eq!(curve.grid_x.len(), 257, "curve {i} grid_x length");
            assert_eq!(curve.grid_y.len(), 257, "curve {i} grid_y length");
        }

        let la = &bundle.layer_a;
        assert_close(la.lo_pct, 1.0, "lo_pct");
        assert_close(la.hi_pct, 99.0, "hi_pct");
        assert_close(la.rail_lo_fraction, 0.0030518043793392844, "rail_lo_fraction");
        assert_close(la.rail_hi_fraction, 0.99, "rail_hi_fraction");
        assert_close(la.gain_bounds.0, 0.02, "gain_bounds.0");
        assert_close(la.gain_bounds.1, 100.0, "gain_bounds.1");
        assert_triple_close(
            la.reference_lo,
            [0.13874608874320984, 0.03604181110858917, 0.02080247173085809],
            "reference_lo",
        );
        assert_triple_close(
            la.reference_hi,
            [0.4708599960803984, 0.15794491887092588, 0.08893278300762175],
            "reference_hi",
        );
        assert_triple_close(
            la.reference_k,
            [1.1943464333096745, 1.3118880757884246, 1.6993638844408396],
            "reference_k",
        );
    }

    // Group G -- load_bundle() fails loudly on malformed method/model tags

    #[test]
    fn group_g_load_bundle_rejects_unsupported_layer_a_method() {
        let malformed_layer_a = r#"{
            "method": "hybrid-exposure-ridge-v2",
            "lo_pct": 1.0,
            "hi_pct": 99.0,
            "rail_lo_fraction": 0.003,
            "rail_hi_fraction": 0.99,
            "gain_bounds": [0.02, 100.0],
            "reference_lo": [0.1, 0.1, 0.1],
            "reference_hi": [0.5, 0.5, 0.5],
            "reference_k": [1.0, 1.0, 1.0]
        }"#;

        let result = parse_bundle(MODEL_JSON, malformed_layer_a, MANIFEST_JSON);
        match result {
            Ok(_) => panic!("expected Err(NikonlookError::Invalid) for unsupported Layer-A method, got Ok(_)"),
            Err(NikonlookError::Invalid(message)) => {
                assert!(
                    message.contains("hybrid-exposure-ridge-v2"),
                    "error message should name the bad method: {message}"
                );
            }
            Err(other) => panic!("expected NikonlookError::Invalid, got {other:?}"),
        }
    }

    #[test]
    fn group_g_load_bundle_rejects_unsupported_model_type() {
        // Only one "DirectPF" substring exists in model.json (the "model"
        // field itself; verified against the vendored file) so a single
        // targeted replacement is safe here.
        let malformed_model = MODEL_JSON.replacen("\"DirectPF\"", "\"NotARealModel\"", 1);
        assert_ne!(malformed_model, MODEL_JSON, "replacement must have changed something");

        let result = parse_bundle(&malformed_model, LAYER_A_JSON, MANIFEST_JSON);
        match result {
            Ok(_) => panic!("expected Err(NikonlookError::Invalid) for unsupported model type, got Ok(_)"),
            Err(NikonlookError::Invalid(message)) => {
                assert!(
                    message.contains("NotARealModel"),
                    "error message should name the bad model type: {message}"
                );
            }
            Err(other) => panic!("expected NikonlookError::Invalid, got {other:?}"),
        }
    }
}
