from __future__ import annotations

import importlib.util
from pathlib import Path
import tempfile
import unittest


PACKAGING_ROOT = Path(__file__).resolve().parents[1]
STAMPER_PATH = PACKAGING_ROOT / "stamp_release_version.py"
SPEC = importlib.util.spec_from_file_location("stamp_release_version", STAMPER_PATH)
assert SPEC is not None and SPEC.loader is not None
STAMPER = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(STAMPER)


TAURI_CONF = """{
  "$schema": "https://schema.tauri.app/config/2",
  "productName": "ScanStudio",
  "version": "0.3.0",
  "identifier": "com.scanstudio.app"
}
"""

PACKAGE_JSON = """{
  "name": "scanstudio-app",
  "version": "0.3.0",
  "private": true
}
"""

CARGO_TOML = """[package]
name = "scanstudio-app"
version = "0.3.0"
edition = "2021"

[dependencies]
tauri = "2.11.4"
"""

# A trimmed but structurally realistic Cargo.lock: an unrelated dependency
# entry before AND after the workspace member's own [[package]] block, so
# the pattern's anchoring (not just "any version line") is under test.
CARGO_LOCK_LF = """# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "anyhow"
version = "1.0.86"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "scanstudio-app"
version = "0.3.0"
dependencies = [
 "tauri",
]

[[package]]
name = "zeroize"
version = "1.8.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
"""


def as_crlf(text: str) -> str:
    return text.replace("\n", "\r\n")


class StampReleaseVersionTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.tauri_conf = self.root / "tauri.conf.json"
        self.package_json = self.root / "package.json"
        self.cargo_toml = self.root / "Cargo.toml"
        self.cargo_lock = self.root / "Cargo.lock"

    def write_fixture(self, cargo_lock_text: str) -> None:
        self.tauri_conf.write_text(TAURI_CONF, encoding="utf-8")
        self.package_json.write_text(PACKAGE_JSON, encoding="utf-8")
        self.cargo_toml.write_text(CARGO_TOML, encoding="utf-8")
        self.cargo_lock.write_text(cargo_lock_text, encoding="utf-8")

    def args(self, version: str) -> list[str]:
        return [
            str(self.tauri_conf),
            str(self.package_json),
            str(self.cargo_toml),
            str(self.cargo_lock),
            version,
        ]

    def test_stamps_all_four_files_with_lf_cargo_lock(self) -> None:
        self.write_fixture(CARGO_LOCK_LF)
        self.assertEqual(STAMPER.main(self.args("1.2.3")), 0)

        self.assertIn('"version": "1.2.3"', self.tauri_conf.read_text())
        self.assertIn('"version": "1.2.3"', self.package_json.read_text())
        self.assertIn('version = "1.2.3"', self.cargo_toml.read_text())

        lock_text = self.cargo_lock.read_text()
        self.assertIn('name = "scanstudio-app"\nversion = "1.2.3"', lock_text)
        # Unrelated packages in the same lockfile must be untouched.
        self.assertIn('name = "anyhow"\nversion = "1.0.86"', lock_text)
        self.assertIn('name = "zeroize"\nversion = "1.8.1"', lock_text)

    def test_stamps_crlf_cargo_lock(self) -> None:
        self.write_fixture(as_crlf(CARGO_LOCK_LF))
        self.assertEqual(STAMPER.main(self.args("1.2.3")), 0)

        lock_bytes = self.cargo_lock.read_bytes()
        self.assertIn(b'name = "scanstudio-app"\r\nversion = "1.2.3"', lock_bytes)
        # The stamp only replaces the captured version value; it must not
        # collapse the file's existing CRLF line endings to LF.
        self.assertIn(b'name = "anyhow"\r\nversion = "1.0.86"', lock_bytes)
        self.assertNotIn(b"\r\r\n", lock_bytes)

    def test_json_and_toml_patterns_are_crlf_agnostic_too(self) -> None:
        # tauri.conf.json/package.json/Cargo.toml go through MULTILINE regexes
        # anchored on ^/$; a Windows checkout can CRLF those files too.
        self.tauri_conf.write_text(as_crlf(TAURI_CONF), encoding="utf-8")
        self.package_json.write_text(as_crlf(PACKAGE_JSON), encoding="utf-8")
        self.cargo_toml.write_text(as_crlf(CARGO_TOML), encoding="utf-8")
        self.cargo_lock.write_text(as_crlf(CARGO_LOCK_LF), encoding="utf-8")

        self.assertEqual(STAMPER.main(self.args("2.0.0")), 0)
        self.assertIn(b'"version": "2.0.0"', self.tauri_conf.read_bytes())
        self.assertIn(b'"version": "2.0.0"', self.package_json.read_bytes())
        self.assertIn(b'version = "2.0.0"\r\n', self.cargo_toml.read_bytes())

    def test_idempotent_restamp_with_same_version_is_a_byte_identical_noop(
        self,
    ) -> None:
        self.write_fixture(CARGO_LOCK_LF)
        self.assertEqual(STAMPER.main(self.args("1.2.3")), 0)
        after_first = {
            path: path.read_bytes()
            for path in (
                self.tauri_conf,
                self.package_json,
                self.cargo_toml,
                self.cargo_lock,
            )
        }

        # Re-stamp the already-stamped tree with the SAME version. Each
        # pattern must still match exactly once (the regex captures whatever
        # value is currently there, not specifically the placeholder), and
        # writing the identical value back must not change any byte.
        self.assertEqual(STAMPER.main(self.args("1.2.3")), 0)
        for path, before in after_first.items():
            self.assertEqual(path.read_bytes(), before, path)

    def test_restamping_with_a_new_version_overwrites_cleanly(self) -> None:
        self.write_fixture(CARGO_LOCK_LF)
        self.assertEqual(STAMPER.main(self.args("1.2.3")), 0)
        self.assertEqual(STAMPER.main(self.args("1.2.4")), 0)

        lock_text = self.cargo_lock.read_text()
        self.assertIn('name = "scanstudio-app"\nversion = "1.2.4"', lock_text)
        self.assertNotIn("1.2.3", lock_text)

    def test_rejects_zero_matches_in_cargo_lock(self) -> None:
        broken_lock = CARGO_LOCK_LF.replace(
            'name = "scanstudio-app"', 'name = "scanstudio-app-renamed"'
        )
        self.write_fixture(broken_lock)
        self.assertEqual(STAMPER.main(self.args("1.2.3")), 1)
        # stamp() raises before writing, so the file that failed to match
        # exactly once is left byte-for-byte untouched rather than partially
        # rewritten -- fail closed, not fail dirty.
        self.assertEqual(self.cargo_lock.read_text(), broken_lock)

    def test_rejects_two_matches_in_cargo_lock(self) -> None:
        duplicated_lock = CARGO_LOCK_LF + (
            '\n[[package]]\nname = "scanstudio-app"\nversion = "0.3.0"\n'
        )
        self.write_fixture(duplicated_lock)
        self.assertEqual(STAMPER.main(self.args("1.2.3")), 1)

    def test_rejects_zero_matches_in_json_file(self) -> None:
        self.write_fixture(CARGO_LOCK_LF)
        self.package_json.write_text('{"name": "scanstudio-app"}\n', encoding="utf-8")
        self.assertEqual(STAMPER.main(self.args("1.2.3")), 1)

    def test_rejects_two_matches_in_json_file(self) -> None:
        self.write_fixture(CARGO_LOCK_LF)
        self.tauri_conf.write_text(
            '{"version": "0.3.0", "nested": {"version": "0.3.0"}}\n',
            encoding="utf-8",
        )
        self.assertEqual(STAMPER.main(self.args("1.2.3")), 1)

    def test_rejects_two_matches_in_cargo_toml(self) -> None:
        self.write_fixture(CARGO_LOCK_LF)
        self.cargo_toml.write_text(
            CARGO_TOML + '\n[workspace.package]\nversion = "0.3.0"\n',
            encoding="utf-8",
        )
        self.assertEqual(STAMPER.main(self.args("1.2.3")), 1)

    def test_missing_file_fails_closed_rather_than_raising(self) -> None:
        self.write_fixture(CARGO_LOCK_LF)
        self.cargo_toml.unlink()
        self.assertEqual(STAMPER.main(self.args("1.2.3")), 1)

    def test_wrong_argument_count_is_a_usage_error(self) -> None:
        self.write_fixture(CARGO_LOCK_LF)
        self.assertEqual(STAMPER.main(self.args("1.2.3")[:-1]), 64)
        self.assertEqual(STAMPER.main([]), 64)

    def test_stamp_release_version_helper_matches_main(self) -> None:
        # The four-file combinator is what both build-and-verify.sh and
        # build-and-verify.ps1 rely on indirectly through main(); exercise it
        # directly too since it is the piece a caller could import instead of
        # shelling out.
        self.write_fixture(CARGO_LOCK_LF)
        STAMPER.stamp_release_version(
            str(self.tauri_conf),
            str(self.package_json),
            str(self.cargo_toml),
            str(self.cargo_lock),
            "9.9.9",
        )
        self.assertIn('"version": "9.9.9"', self.tauri_conf.read_text())
        self.assertIn('name = "scanstudio-app"\nversion = "9.9.9"', self.cargo_lock.read_text())

    def test_stamp_helper_raises_stamp_error_on_bad_match_count(self) -> None:
        self.write_fixture(CARGO_LOCK_LF)
        self.package_json.write_text('{"no_version_here": true}\n', encoding="utf-8")
        with self.assertRaises(STAMPER.StampError):
            STAMPER.stamp_release_version(
                str(self.tauri_conf),
                str(self.package_json),
                str(self.cargo_toml),
                str(self.cargo_lock),
                "1.2.3",
            )


if __name__ == "__main__":
    unittest.main()
