//! ScanStudio color profile embedded into C41 derivative metadata.
//!
//! ScanStudio's positive/preview renderer writes Adobe RGB (1998)-compatible
//! encoded pixel values for the C41 color-negative tint (see
//! `render_positive`'s doc comment and `processing/nikonlook.rs`). For those
//! files to be color-accurate when opened in an editor, the derivative TIFF
//! must label them with a matching Adobe RGB (1998)-compatible ICC profile —
//! otherwise they silently fall back to unprofiled/default sRGB.
//!
//! The profile is generated by `moxcms` (BSD-3-Clause OR Apache-2.0) from the
//! public-domain Adobe RGB (1998) matrix/TRC parameters, then identified as a
//! ScanStudio-authored compatible profile. No Adobe-authored or
//! Nikon-proprietary ICC bytes are redistributed in this repository (see
//! `processing/nikonlook.rs` and `THIRD_PARTY_NOTICES.md`).

use std::sync::OnceLock;

use crate::domain;
use crate::protocol;

const PROFILE_DESCRIPTION: &str = "ScanStudio RGB (compatible with Adobe RGB (1998))";

// ICC dateTimeNumber: 2026-08-02 00:00:00 UTC, six big-endian u16 values.
// moxcms 0.8.1 otherwise stamps the wall clock during encode(). Normalizing
// this header-only field makes independently rendered derivatives reproducible.
const CREATION_DATE: [u8; 12] = [
    0x07, 0xea, 0x00, 0x08, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

fn build_profile_bytes() -> Result<Vec<u8>, String> {
    let mut profile = moxcms::ColorProfile::new_adobe_rgb();
    profile.description = Some(moxcms::ProfileText::Localizable(vec![
        moxcms::LocalizableString::new(
            "en".to_string(),
            "US".to_string(),
            PROFILE_DESCRIPTION.to_string(),
        ),
    ]));
    let mut bytes = profile.encode().map_err(|error| error.to_string())?;
    if bytes.len() < 128 {
        return Err(format!(
            "moxcms returned a truncated {}-byte ICC profile",
            bytes.len()
        ));
    }
    bytes[24..36].copy_from_slice(&CREATION_DATE);
    // A profile ID is the MD5 of selected profile bytes. ICC permits all-zero
    // to mean not calculated; explicitly clear it after changing the date so
    // it cannot become stale if the encoder starts computing IDs later.
    bytes[84..100].fill(0);
    moxcms::ColorProfile::new_from_slice(&bytes)
        .map_err(|error| format!("generated ICC profile failed validation: {error}"))?;
    Ok(bytes)
}

/// The compatible ICC profile bytes, generated once per process and cached.
fn profile_bytes() -> Result<&'static [u8], domain::EngineError> {
    static CACHE: OnceLock<Result<Vec<u8>, String>> = OnceLock::new();
    let encoded = CACHE.get_or_init(build_profile_bytes);
    match encoded {
        Ok(bytes) => Ok(bytes),
        Err(message) => Err(domain::EngineError::new(
            protocol::ErrorCode::Internal,
            format!("failed to generate ScanStudio RGB ICC profile: {message}"),
        )),
    }
}

/// Returns the ScanStudio-authored, Adobe RGB (1998)-compatible ICC bytes to
/// embed in a
/// derivative's `IccProfile` tag. Generation is fail-closed: an encoder
/// failure is an engine error rather than a silently unlabeled derivative.
pub fn scanstudio_rgb_icc_profile() -> Result<Vec<u8>, domain::EngineError> {
    Ok(profile_bytes()?.to_vec())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generated profile must re-parse as a valid ICC RGB profile whose
    /// red/green/blue matrix columns match the published Adobe RGB (1998)
    /// D50 primaries — this is a parser-based validity check, not a byte
    /// comparison (the encoder stamps a current timestamp in the header).
    #[test]
    fn generated_adobergb_profile_is_valid_and_matches_adobergb_primaries() {
        let bytes = scanstudio_rgb_icc_profile().expect("profile encodes");
        let profile =
            moxcms::ColorProfile::new_from_slice(&bytes).expect("encoded profile re-parses");

        // ICC XYZType values are signed 15.16 fixed point; allow the
        // round-trip quantization imposed by that representation.
        let tolerance = 3e-4_f64;
        let check = |actual: moxcms::Xyzd, expected: (f64, f64, f64)| {
            assert!(
                (actual.x - expected.0).abs() < tolerance
                    && (actual.y - expected.1).abs() < tolerance
                    && (actual.z - expected.2).abs() < tolerance,
                "colorant mismatch: {actual:?} vs {expected:?}"
            );
        };
        check(profile.red_colorant, (0.60974, 0.31111, 0.01947));
        check(profile.green_colorant, (0.20528, 0.62567, 0.06087));
        check(profile.blue_colorant, (0.14919, 0.06322, 0.74457));
        assert!(
            matches!(profile.color_space, moxcms::DataColorSpace::Rgb),
            "compatible profile must declare an RGB color space"
        );
        assert_eq!(profile.creation_date_time.year, 2026);
        assert_eq!(profile.creation_date_time.month, 8);
        assert_eq!(profile.creation_date_time.day_of_the_month, 2);
        assert!(matches!(
            profile.description,
            Some(moxcms::ProfileText::Localizable(ref values))
                if values.iter().any(|value| value.value == PROFILE_DESCRIPTION)
        ));
    }

    /// Generation is fail-closed (an encoder error surfaces, never silent).
    #[test]
    fn generation_is_deterministic_across_fresh_encodes() {
        let first = build_profile_bytes().expect("first encode");
        let second = build_profile_bytes().expect("second encode");
        assert_eq!(first, second, "freshly encoded bytes must be stable");
        assert_eq!(&first[24..36], &CREATION_DATE);
        assert!(first[84..100].iter().all(|byte| *byte == 0));
        assert_eq!(&first[36..40], b"acsp");
        assert_eq!(
            u32::from_be_bytes(first[0..4].try_into().unwrap()) as usize,
            first.len()
        );
    }
}
